---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '09:00'
      timezone: 'Europe/Oslo'
      day: 'monday'
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - jfrog-artifactory
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
      major-updates:
        applies-to: version-updates
        update-types:
          - 'major'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    allow:
      - dependency-type: direct
      - dependency-type: production
  - package-ecosystem: 'npm'
    directories:
      - '/packages/**/*'
    registries:
      - jfrog-artifactory
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
      major-updates:
        applies-to: version-updates
        update-types:
          - 'major'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
    allow:
      - dependency-type: direct
      - dependency-type: production
