---
version: 2
registries:
  jfrog-artifactory:
    type: npm-registry
    url: https://entur2.jfrog.io/entur2
    token: ${{secrets.ARTIFACTORY_AUTH_TOKEN}}
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'chore(gha/deps)'
    schedule:
      interval: 'weekly'
      time: '09:00'
      timezone: 'Europe/Oslo'
      day: 'monday'
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - jfrog-artifactory
    commit-message:
      prefix: 'chore(root/deps)'
    groups:
      dev-deps:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - 'minor'
          - 'patch'
          - 'major'
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
      major-updates:
        applies-to: version-updates
        update-types:
          - 'major'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
    allow:
      - dependency-type: direct
      - dependency-type: production
      - dependency-type: development
  - package-ecosystem: 'npm'
    directories:
      - '/packages/**/*'
    registries:
      - jfrog-artifactory
    commit-message:
      prefix: 'chore(packages/deps)'
    groups:
      dev-deps:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - 'minor'
          - 'patch'
          - 'major'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
    allow:
      - dependency-type: direct
      - dependency-type: production
      - dependency-type: development
  - package-ecosystem: 'npm'
    directories:
      - '/apps/**/*'
    registries:
      - jfrog-artifactory
    commit-message:
      prefix: 'chore(apps/deps)'
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
      major-updates:
        applies-to: version-updates
        update-types:
          - 'major'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
    allow:
      - dependency-type: direct
      - dependency-type: production
