image: node:10.15.3

pipelines:
  default:
    - step:
        name: Test
        script:
          - yarn && yarn test

    - step:
        name: Build
        script:
          - yarn && yarn build
        artifacts:
          - build/**

    - step:
        name: Deploy to Firebase
        deployment: default
        script:
          - pipe: atlassian/firebase-deploy:0.3.3
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN