name: 'Install and cache dependencies'
description: 'Installs dependencies for a yarn 2 monorepo and caches the result'
inputs:
  cache-key:
    description: 'Cache key for Yarn dependencies'
    required: true
runs:
  using: 'composite'
  steps:
    # - name: Use Node.js 16
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        # node-version: '16'
        node-version: '18'

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Enable Corepack
      run: yarn set version berry
      shell: bash

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: '.yarn/cache'
        key: ${{ inputs.cache-key }}

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
