import flat from 'flat';

const { unflatten } = flat;

type Variable = {
  name: string;
  value: string;
  var: string;
  rootAlias: string;
};
type VariableMode = {
  mode: { name: string };
  color: Variable[];
  number: Variable[];
};
export type VariableSet = {
  css: KeyValueSet;
  scss: KeyValueSet;
  less: KeyValueSet;
  js: KeyValueSet;
  mode: string;
  usesAlias: boolean;
};
type KeyValueSet = {
  key: string;
  value: string;
  sanitizedValue?: string;
};
export type ColorFileData = {
  outputString: string;
  outputFileName: string;
  packageName?: string;
};

const SUPPORTED_COLOR_MODES = ['light', 'dark'];

export function createVariableSet(
  fileData: string,
  valueType: 'color' | 'number' = 'color',
) {
  const dataUnformatted = JSON.parse(fileData);
  const variablesFormattedAndMappedToModes: VariableSet[] =
    dataUnformatted[0].values.reduce(
      (allComponentVariables: VariableSet[], variableMode: VariableMode) => {
        const variablesArray =
          valueType === 'color' ? variableMode.color : variableMode.number;
        const variablesFormattedForMode: VariableSet[] = variablesArray.map(
          (variable: Variable) => {
            const variableNameInKebabCase = toKebabCase(variable.name);
            const varNameInKebabCase = toKebabCase(variable.var);
            const variableValue = variable.value;
            const modeName = variableMode.mode.name.toLowerCase();
            const usesAlias = varNameInKebabCase !== '';

            return {
              css: {
                key: `--${variableNameInKebabCase}`,
                value: usesAlias
                  ? `var(--${varNameInKebabCase})`
                  : variableValue,
              },
              scss: {
                key: `$${variableNameInKebabCase}`,
                value: usesAlias ? `$${varNameInKebabCase}` : variableValue,
                sanitizedValue: usesAlias
                  ? `#{$${varNameInKebabCase}}`
                  : variableValue,
              },
              less: {
                key: `@${variableNameInKebabCase}`,
                value: usesAlias ? `@${varNameInKebabCase}` : variableValue,
              },
              js: {
                key: `${
                  SUPPORTED_COLOR_MODES.includes(modeName) ? modeName + '.' : ''
                }${toFlattenedJSObjectKey(variable.name)}`,
                value: variableValue,
              },
              mode: modeName,
              usesAlias: usesAlias,
            };
          },
        );

        return [...allComponentVariables, ...variablesFormattedForMode];
      },
      [],
    );
  return variablesFormattedAndMappedToModes;
}

// Backward compatibility
export function createColorSet(fileData: string) {
  return createVariableSet(fileData, 'color');
}

const WARNING_TEXT = `/* DO NOT CHANGE!*/
/* This file is automatically generated from @entur/tokens! Changes will be overwritten. */`;

function createVariablesOutputString({
  variableSet,
  keyType,
  valueType,
  withColorMode,
  importFileNames,
}: {
  variableSet: VariableSet[];
  keyType: 'css' | 'scss' | 'less';
  valueType: 'css' | 'scss' | 'less';
  withColorMode?: boolean;
  importFileNames?: string[];
}) {
  const needsRoot = keyType === 'css';
  const needsImport = variableSet.some(variable => variable.usesAlias);

  // Separate color variables (light/dark modes) from size variables (view modes)
  const colorVariables = variableSet.filter(v =>
    ['light', 'dark'].includes(v.mode),
  );
  const sizeVariables = variableSet.filter(v =>
    ['standard', 'compact', 'display'].includes(v.mode),
  );

  if (withColorMode) {
    if (needsImport && importFileNames) {
      const importString = createImportStatementString({
        fileNames: importFileNames,
        extension: valueType,
        includeAs: needsImport && valueType === 'scss',
      });
      const colorModeString =
        colorVariables.length > 0 ? stringWithColorMode(colorVariables) : '';
      const viewModeString =
        sizeVariables.length > 0 ? stringWithViewMode(sizeVariables) : '';
      return `${importString}
${colorModeString}${viewModeString}`;
    }
    const colorModeString =
      colorVariables.length > 0 ? stringWithColorMode(colorVariables) : '';
    const viewModeString =
      sizeVariables.length > 0 ? stringWithViewMode(sizeVariables) : '';
    return `${colorModeString}${viewModeString}`;
  } else {
    if (needsImport && importFileNames) {
      const importString = createImportStatementString({
        fileNames: importFileNames,
        extension: valueType,
        includeAs: needsImport && valueType === 'scss',
      });
      const variablesString = stringWithoutColorMode(variableSet, needsRoot);
      return `${importString}
      ${variablesString}
      `;
    }
    return stringWithoutColorMode(variableSet, needsRoot);
  }

  function stringWithColorMode(variableSet: VariableSet[]) {
    const outputString = `
${WARNING_TEXT}
[data-color-mode='light'],
:root {
  ${variableSet
    .filter(variable => variable?.mode === 'light')
    .map(variable => {
      const variableKey = variable[keyType].key;
      const variableValue =
        keyType === 'css' && valueType === 'scss'
          ? variable[valueType].sanitizedValue
          : variable[valueType].value;
      return `${variableKey}: ${variableValue};`;
    })
    .join('\n  ')}
}

[data-color-mode='dark'] {
  ${variableSet
    .filter(variable => variable?.mode === 'dark')
    .map(variable => {
      const variableKey = variable[keyType].key;
      const variableValue =
        keyType === 'css' && valueType === 'scss'
          ? variable[valueType].sanitizedValue
          : variable[valueType].value;
      return `${variableKey}: ${variableValue};`;
    })
    .join('\n  ')}
}
`;

    return outputString;
  }

  function stringWithViewMode(variableSet: VariableSet[]) {
    const outputString = `
[data-view-mode='standard'],
:root {
  ${variableSet
    .filter(variable => variable?.mode === 'standard')
    .map(variable => {
      const variableKey = variable[keyType].key;
      const variableValue =
        keyType === 'css' && valueType === 'scss'
          ? variable[valueType].sanitizedValue
          : variable[valueType].value;
      return `${variableKey}: ${variableValue};`;
    })
    .join('\n  ')}
}

[data-view-mode='compact'] {
  ${variableSet
    .filter(variable => variable?.mode === 'compact')
    .map(variable => {
      const variableKey = variable[keyType].key;
      const variableValue =
        keyType === 'css' && valueType === 'scss'
          ? variable[valueType].sanitizedValue
          : variable[valueType].value;
      return `${variableKey}: ${variableValue};`;
    })
    .join('\n  ')}
}

[data-view-mode='display'] {
  ${variableSet
    .filter(variable => variable?.mode === 'display')
    .map(variable => {
      const variableKey = variable[keyType].key;
      const variableValue =
        keyType === 'css' && valueType === 'scss'
          ? variable[valueType].sanitizedValue
          : variable[valueType].value;
      return `${variableKey}: ${variableValue};`;
    })
    .join('\n  ')}
}
`;

    return outputString;
  }

  function stringWithoutColorMode(
    variableSet: VariableSet[],
    needsRoot: boolean,
  ) {
    const outputString = `
${WARNING_TEXT}
${needsRoot ? ':root {' : ''}
${needsRoot ? '\t' : ''}${variableSet
      .map(variable => {
        const variableKey = variable[keyType].key;
        const variableValue =
          keyType === 'css' && valueType === 'scss'
            ? variable[valueType].sanitizedValue
            : variable[valueType].value;
        return `${variableKey}: ${variableValue};`;
      })
      .join(`\n${needsRoot ? '\t' : ''}`)}
${needsRoot ? '}' : ''}
  `;
    return outputString;
  }
  function createImportStatementString({
    fileNames,
    extension,
    includeAs,
  }: {
    fileNames: string[];
    extension: 'css' | 'scss' | 'less';
    includeAs?: boolean;
  }) {
    const IMPORT_SYNTAX = { css: '@import', scss: '@use', less: '@import' };
    const asStatement = includeAs ? ' as *' : '';
    const importStatements = fileNames.map(fileName => {
      const importPath = `'@entur/tokens/dist/${fileName}.${extension}'`;
      return `${extension === 'scss' ? '@forward ' + importPath + ';\n' : ''}${
        IMPORT_SYNTAX[extension]
      } ${importPath}${asStatement};`;
    });

    return importStatements.join('\n');
  }
}

export function createVariablesFileData({
  variableSet,
  keyType,
  valueType,
  name,
  outputToPackages,
  withColorMode = false,
  importFileNames,
}: {
  variableSet: VariableSet[];
  keyType: 'css' | 'scss' | 'less';
  valueType: 'css' | 'scss' | 'less';
  name: string;
  outputToPackages?: string[];
  withColorMode?: boolean;
  importFileNames?: string[];
}) {
  let outputString = '';

  if (outputToPackages) {
    let outputData: ColorFileData[] = [];
    outputToPackages.forEach(packageName => {
      outputString = '';
      const variablesForCurrentPackage = variableSet.filter(variable => {
        const scssKey = variable.scss.key;
        const cssKey = variable.css.key;
        // Handle both naming patterns:
        // 1. Color variables: $components-{package}-... (e.g., $components-button-...)
        // 2. Size variables: ${package}-... (e.g., $button-border-...)
        return (
          scssKey.includes(`-${packageName}-`) ||
          scssKey.startsWith(`$${packageName}-`) ||
          cssKey.startsWith(`--${packageName}-`)
        );
      });

      if (variablesForCurrentPackage.length === 0) {
        return;
      }

      if (packageName === 'travel') {
        outputString += createVariablesOutputString({
          variableSet: variablesForCurrentPackage,
          keyType,
          valueType,
          withColorMode: true,
          importFileNames: ['semantic', 'transport'],
        });
      } else {
        outputString += createVariablesOutputString({
          variableSet: variablesForCurrentPackage,
          keyType,
          valueType,
          withColorMode: true,
          importFileNames: ['semantic'],
        });
      }

      outputData.push({
        outputString,
        outputFileName: `${name}.scss`,
        packageName,
      });
    });
    return outputData;
  }

  switch (name) {
    case 'base':
      outputString += createVariablesOutputString({
        variableSet,
        keyType,
        valueType,
        withColorMode: true,
        importFileNames: ['semantic', 'transport'],
      });
      break;
    case 'semantic':
      outputString += createVariablesOutputString({
        variableSet,
        keyType,
        valueType,
        withColorMode: false,
        importFileNames: ['primitive'],
      });
      break;
    case 'data':
      outputString += createVariablesOutputString({
        variableSet,
        keyType,
        valueType,
        withColorMode: true,
      });
      break;
    default:
      outputString += createVariablesOutputString({
        variableSet,
        keyType,
        valueType,
        withColorMode,
        importFileNames,
      });
  }

  return [
    { outputString, outputFileName: `${name}.${valueType}` },
  ] as ColorFileData[];
}

// Backward compatibility
export function createColorsFileData({
  colorSet,
  keyType,
  valueType,
  name,
  outputToPackages,
  withColorMode = false,
  importFileNames,
}: {
  colorSet: VariableSet[];
  keyType: 'css' | 'scss' | 'less';
  valueType: 'css' | 'scss' | 'less';
  name: string;
  outputToPackages?: string[];
  withColorMode?: boolean;
  importFileNames?: string[];
}) {
  return createVariablesFileData({
    variableSet: colorSet,
    keyType,
    valueType,
    name,
    outputToPackages,
    withColorMode,
    importFileNames,
  });
}

export function createJSColorFileData({
  variables,
  name,
}: {
  variables: VariableSet[];
  name: string;
}) {
  const jsVariables = variables.map(color => ({
    [color?.js.key]: color?.js.value,
  }));
  const jsVariablesObject = Object.assign({}, ...jsVariables);
  const unflattenedJSVariablesObject = unflatten(jsVariablesObject);

  const outputString = `${WARNING_TEXT}
 export const ${name} = ${JSON.stringify(unflattenedJSVariablesObject)}
 `;

  return { outputString: outputString, outputFileName: `${name}.ts` };
}

function toKebabCase(name: string) {
  return name.replace(/\//g, '-').replace(/\s/g, '').toLowerCase();
}

function toFlattenedJSObjectKey(name: string) {
  const nameWithoutSpacesAndDashes = name
    .toLowerCase()
    .replace(/\s(\w)/g, (_, letter) => letter.toUpperCase())
    .replace(/-(\w)/g, (_, letter) => letter.toUpperCase());
  const nameArray = nameWithoutSpacesAndDashes.split('/');

  const nameArrayWithStringNumbers = nameArray.map(namePart => {
    if (!isNaN(Number(namePart.charAt(0)))) {
      return `_${namePart}`;
    }
    return namePart;
  });
  return nameArrayWithStringNumbers.join('.');
}
