// OKR-rapport data for Entur Linje designsystem
// Periode: 2025 (Q1–Q4) og Q1 2026
// Kilde: Jira ETU-prosjektet, board 173
//
// VIKTIG: Dette er et representativt eksempel-datasett.
// Atlassian MCP-verktøy var ikke tilgjengelig ved generering.
// Oppdater med ekte data fra Jira ved neste kvartalsslutt.
// JQL-søk:
//   project = ETU AND labels in (linje, designsystem, design-system)
//   AND created >= "2025-01-01" AND created <= "2026-03-31"
//   ORDER BY created ASC

export type IssueStatus = 'Fullfort' | 'Pagar' | 'IkkeStartet';
export type IssueCategory = 'okr' | 'support' | 'vedlikehold';
export type Kvartal = 'Q1-2025' | 'Q2-2025' | 'Q3-2025' | 'Q4-2025' | 'Q1-2026';

export type JiraIssue = {
  key: string;
  summary: string;
  status: IssueStatus;
  category: IssueCategory;
  labels: string[];
  kvartal: Kvartal;
  team?: string;
  okrKobling?: string;
  issuetype: string;
};

// ============================================================
// Q1 2025 — januar til mars
// ============================================================

export const Q1_2025_OKR: JiraIssue[] = [
  {
    key: 'ETU-63201',
    summary: 'Ny komponent: TimeInput – tidsinput for reiseplanlegging',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q1-2025',
    labels: ['okr-q1-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: Øke komponentbiblioteket med 3 nye komponenter i Q1',
    issuetype: 'Story',
  },
  {
    key: 'ETU-63145',
    summary: 'Implementer dark mode / contrast mode for alle kjernekomponenter',
    status: 'Pagar',
    category: 'okr',
    kvartal: 'Q1-2025',
    labels: ['okr-q1-2025', 'tokens', 'linje', 'a11y'],
    okrKobling: 'OKR: Universell utforming – 100% kontrastmodus-dekning',
    issuetype: 'Epic',
  },
  {
    key: 'ETU-63089',
    summary: 'Design token-pipeline: automatisk sync fra Figma til kode',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q1-2025',
    labels: ['okr-q1-2025', 'tokens', 'linje', 'figma'],
    okrKobling: 'OKR: Reduser Figma-til-kode-tid med 50%',
    issuetype: 'Story',
  },
  {
    key: 'ETU-62988',
    summary: 'Ny komponent: FileUpload – filvedlegg for skjemaflyt',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q1-2025',
    labels: ['okr-q1-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: Øke komponentbiblioteket med 3 nye komponenter i Q1',
    issuetype: 'Story',
  },
  {
    key: 'ETU-62901',
    summary: 'Oppdater typografi-tokens til ny Nationale-variantskala',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q1-2025',
    labels: ['okr-q1-2025', 'tokens', 'typografi', 'linje'],
    okrKobling: 'OKR: Reduser Figma-til-kode-tid med 50%',
    issuetype: 'Story',
  },
  {
    key: 'ETU-62856',
    summary: 'Dokumentasjon: kom-i-gang-guide for nye konsumentteam',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q1-2025',
    labels: ['okr-q1-2025', 'dokumentasjon', 'linje'],
    okrKobling: 'OKR: Reduser onboarding-tid for nye team til under 1 dag',
    issuetype: 'Story',
  },
  {
    key: 'ETU-62744',
    summary: 'Tilgjengelighetstesting: screen reader-gjennomgang av Dropdown',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q1-2025',
    labels: ['okr-q1-2025', 'a11y', 'linje'],
    okrKobling: 'OKR: Universell utforming – 100% kontrastmodus-dekning',
    issuetype: 'Task',
  },
  {
    key: 'ETU-62698',
    summary: 'Ny komponent: Pagination – navigering i lister og tabeller',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q1-2025',
    labels: ['okr-q1-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: Øke komponentbiblioteket med 3 nye komponenter i Q1',
    issuetype: 'Story',
  },
  {
    key: 'ETU-62632',
    summary: 'Etabler Storybook som primær sandkasse for komponent-utvikling',
    status: 'Pagar',
    category: 'okr',
    kvartal: 'Q1-2025',
    labels: ['okr-q1-2025', 'verktoy', 'linje'],
    okrKobling: 'OKR: Reduser Figma-til-kode-tid med 50%',
    issuetype: 'Epic',
  },
  {
    key: 'ETU-62589',
    summary: 'Semantic versioning og release notes automatisering',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q1-2025',
    labels: ['okr-q1-2025', 'infrastruktur', 'linje'],
    okrKobling: 'OKR: Reduser onboarding-tid for nye team til under 1 dag',
    issuetype: 'Task',
  },
  {
    key: 'ETU-62501',
    summary: 'A11y: keyboard navigation audit for alle interaktive komponenter',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q1-2025',
    labels: ['okr-q1-2025', 'a11y', 'linje'],
    okrKobling: 'OKR: Universell utforming – 100% kontrastmodus-dekning',
    issuetype: 'Task',
  },
  {
    key: 'ETU-62388',
    summary: 'Ikonbibliotek: 40 nye reise-ikoner fra Figma-eksport',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q1-2025',
    labels: ['okr-q1-2025', 'ikoner', 'linje'],
    okrKobling: 'OKR: Øke komponentbiblioteket med 3 nye komponenter i Q1',
    issuetype: 'Story',
  },
];

export const Q1_2025_SUPPORT: JiraIssue[] = [
  {
    key: 'ETU-63312',
    summary: 'Hjelp til migrering fra v2 til v3 – team Reiseplanlegging',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'migrering'],
    team: 'Reiseplanlegging',
    issuetype: 'Support',
  },
  {
    key: 'ETU-63289',
    summary: 'Bug: DatePicker viser feil tidssone for Oslo-brukere',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'bug', 'datepicker'],
    team: 'Billett & Betaling',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-63156',
    summary: 'Rådgiving: fargebruk i kart-komponent – universell utforming',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'a11y', 'radgivning'],
    team: 'Kart & Sanntid',
    issuetype: 'Support',
  },
  {
    key: 'ETU-63098',
    summary: 'Bug: Button-komponent mister fokus-ring i kontrast-modus',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'bug', 'button', 'a11y'],
    team: 'Platform',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-63034',
    summary: 'Pair programming: implementering av Modal i Sanntidsappen',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'pair-programming'],
    team: 'Sanntid',
    issuetype: 'Support',
  },
  {
    key: 'ETU-62967',
    summary: 'Spørsmål: riktig bruk av GridItem breakpoints pa mobil',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'sporsmal'],
    team: 'Reiseplanlegging',
    issuetype: 'Support',
  },
  {
    key: 'ETU-62834',
    summary: 'Bug: TextField close-button har feil farger i contrast mode',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'bug', 'textfield'],
    team: 'Platform',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-62778',
    summary: 'Review: Chip-komponent custom styling – team Kundeservice',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'review'],
    team: 'Kundeservice',
    issuetype: 'Task',
  },
  {
    key: 'ETU-62712',
    summary: 'Hjelp: oppsett av @entur/tokens i nytt Next.js-prosjekt',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'onboarding'],
    team: 'Entur.no',
    issuetype: 'Support',
  },
  {
    key: 'ETU-62645',
    summary: 'Bug: TravelHeader kollaps ikke riktig pa 768px breakpoint',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'bug', 'travel'],
    team: 'Reiseplanlegging',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-62590',
    summary: 'Konsultasjon: ikonstørrelse-standard for navigasjonsmenyer',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'radgivning', 'ikoner'],
    team: 'Sanntid',
    issuetype: 'Support',
  },
  {
    key: 'ETU-62528',
    summary: 'Bug: DatePicker timezone-bug ved sommertid',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'bug', 'datepicker'],
    team: 'Billett & Betaling',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-62444',
    summary: 'Pair programming: Tooltip implementering for kart-markorer',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2025',
    labels: ['support', 'pair-programming'],
    team: 'Kart & Sanntid',
    issuetype: 'Support',
  },
];

export const Q1_2025_VEDLIKEHOLD: JiraIssue[] = [
  {
    key: 'ETU-63178',
    summary: 'Oppdater avhengigheter: React 17 patch og TypeScript 5.9',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q1-2025',
    labels: ['vedlikehold', 'deps'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-63112',
    summary: 'Refaktorering: fjern legacy className-mønstre fra v1',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q1-2025',
    labels: ['vedlikehold', 'refaktorering'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-62923',
    summary: 'CI/CD: fikse flakey tester i DatePicker-suite',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q1-2025',
    labels: ['vedlikehold', 'test', 'ci'],
    issuetype: 'Bug',
  },
  {
    key: 'ETU-62811',
    summary: 'Lerna: oppgrader til v8 og konfigurer Nx caching riktig',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q1-2025',
    labels: ['vedlikehold', 'infrastruktur'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-62666',
    summary: 'Gatsby-docs: fikse broken links etter side-restrukturering',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q1-2025',
    labels: ['vedlikehold', 'dokumentasjon'],
    issuetype: 'Bug',
  },
  {
    key: 'ETU-62555',
    summary: 'Oppdater Stylelint-regler til v15 API',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q1-2025',
    labels: ['vedlikehold', 'lint'],
    issuetype: 'Task',
  },
];

// ============================================================
// Q2 2025 — april til juni
// ============================================================

export const Q2_2025_OKR: JiraIssue[] = [
  {
    key: 'ETU-64101',
    summary: 'Ny komponent: Stepper – flertrinnsskjema med fremdriftsindikator',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q2-2025',
    labels: ['okr-q2-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: Øke komponentbiblioteket med 4 nye komponenter i Q2',
    issuetype: 'Story',
  },
  {
    key: 'ETU-64089',
    summary: 'Storybook: publiser offentlig komponent-sandkasse pa linje.entur.no',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q2-2025',
    labels: ['okr-q2-2025', 'verktoy', 'linje', 'storybook'],
    okrKobling: 'OKR: Reduser Figma-til-kode-tid med 50%',
    issuetype: 'Epic',
  },
  {
    key: 'ETU-64034',
    summary: 'Ny komponent: ColorSwatch – fargevelger for token-visning',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q2-2025',
    labels: ['okr-q2-2025', 'komponent', 'tokens', 'linje'],
    okrKobling: 'OKR: Øke komponentbiblioteket med 4 nye komponenter i Q2',
    issuetype: 'Story',
  },
  {
    key: 'ETU-63978',
    summary: 'A11y: ARIA-audit av samtlige skjema-komponenter',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q2-2025',
    labels: ['okr-q2-2025', 'a11y', 'linje'],
    okrKobling: 'OKR: Universell utforming – WCAG 2.2 AA for alle komponenter',
    issuetype: 'Task',
  },
  {
    key: 'ETU-63921',
    summary: 'Token-versjonering: semantisk changelog for designendringer',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q2-2025',
    labels: ['okr-q2-2025', 'tokens', 'linje'],
    okrKobling: 'OKR: Reduser Figma-til-kode-tid med 50%',
    issuetype: 'Story',
  },
  {
    key: 'ETU-63867',
    summary: 'Ny komponent: ProgressBar – fremdriftsindikator for lasteprosesser',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q2-2025',
    labels: ['okr-q2-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: Øke komponentbiblioteket med 4 nye komponenter i Q2',
    issuetype: 'Story',
  },
  {
    key: 'ETU-63812',
    summary: 'Dokumentasjon: interaktive kodeeksempler for alle Button-varianter',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q2-2025',
    labels: ['okr-q2-2025', 'dokumentasjon', 'linje'],
    okrKobling: 'OKR: Reduser onboarding-tid for nye team til under 1 dag',
    issuetype: 'Story',
  },
  {
    key: 'ETU-63756',
    summary: 'Kontrast-modus: implementer for Modal, Tooltip og Popover',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q2-2025',
    labels: ['okr-q2-2025', 'a11y', 'linje'],
    okrKobling: 'OKR: Universell utforming – WCAG 2.2 AA for alle komponenter',
    issuetype: 'Task',
  },
  {
    key: 'ETU-63701',
    summary: 'Ny komponent: Banner – globale varselmeldinger pa topp av siden',
    status: 'Pagar',
    category: 'okr',
    kvartal: 'Q2-2025',
    labels: ['okr-q2-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: Øke komponentbiblioteket med 4 nye komponenter i Q2',
    issuetype: 'Story',
  },
  {
    key: 'ETU-63644',
    summary: 'Figma-bibliotek: synkroniser komponent-states med kode-props',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q2-2025',
    labels: ['okr-q2-2025', 'figma', 'linje'],
    okrKobling: 'OKR: Reduser Figma-til-kode-tid med 50%',
    issuetype: 'Task',
  },
];

export const Q2_2025_SUPPORT: JiraIssue[] = [
  {
    key: 'ETU-64198',
    summary: 'Bug: Select-dropdown lukker seg ikke pa iOS Safari',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q2-2025',
    labels: ['support', 'bug', 'dropdown'],
    team: 'Billett & Betaling',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-64156',
    summary: 'Hjelp: implementer søkbar Dropdown med async data – Ruteplanlegging',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q2-2025',
    labels: ['support', 'pair-programming'],
    team: 'Ruteplanlegging',
    issuetype: 'Support',
  },
  {
    key: 'ETU-64112',
    summary: 'Rådgiving: fargepalettvalg for nye kart-overlay-lag',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q2-2025',
    labels: ['support', 'radgivning'],
    team: 'Kart & Sanntid',
    issuetype: 'Support',
  },
  {
    key: 'ETU-64067',
    summary: 'Bug: Modal-fokus fanget ikke i Firefox ved tastaturnavigasjon',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q2-2025',
    labels: ['support', 'bug', 'modal', 'a11y'],
    team: 'Platform',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-63989',
    summary: 'Review: ny landingsside for Entur.no – Linje-komponenter',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q2-2025',
    labels: ['support', 'review'],
    team: 'Entur.no',
    issuetype: 'Task',
  },
  {
    key: 'ETU-63934',
    summary: 'Spørsmål: bruk av SkeletonLoader under datahenting',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q2-2025',
    labels: ['support', 'sporsmal'],
    team: 'Reiseplanlegging',
    issuetype: 'Support',
  },
  {
    key: 'ETU-63878',
    summary: 'Pair programming: Table-komponent med sortering og filtrering',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q2-2025',
    labels: ['support', 'pair-programming'],
    team: 'Innsikt',
    issuetype: 'Support',
  },
  {
    key: 'ETU-63823',
    summary: 'Bug: Accordion animasjon hakker pa lav-ytelse enheter',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q2-2025',
    labels: ['support', 'bug', 'expand'],
    team: 'Kundeservice',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-63769',
    summary: 'Konsultasjon: responsiv layout for billettvisning',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q2-2025',
    labels: ['support', 'radgivning'],
    team: 'Billett & Betaling',
    issuetype: 'Support',
  },
  {
    key: 'ETU-63712',
    summary: 'Hjelp: migrering av Chip-komponenter til ny API',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q2-2025',
    labels: ['support', 'migrering'],
    team: 'Sanntid',
    issuetype: 'Support',
  },
  {
    key: 'ETU-63657',
    summary: 'Bug: Tab-komponent viser feil underline-farge i Safari',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q2-2025',
    labels: ['support', 'bug', 'tab'],
    team: 'Platform',
    issuetype: 'Bug',
  },
];

export const Q2_2025_VEDLIKEHOLD: JiraIssue[] = [
  {
    key: 'ETU-64234',
    summary: 'Yarn: migrer fra v3 til v4 og oppdater .yarnrc.yml',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q2-2025',
    labels: ['vedlikehold', 'infrastruktur'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-64178',
    summary: 'Vite: oppgrader til v6 – oppdater alle vite.config.ts',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q2-2025',
    labels: ['vedlikehold', 'build'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-64023',
    summary: 'Gatsby: fikse hydration-feil etter React 18 oppgradering',
    status: 'Pagar',
    category: 'vedlikehold',
    kvartal: 'Q2-2025',
    labels: ['vedlikehold', 'gatsby', 'react'],
    issuetype: 'Bug',
  },
  {
    key: 'ETU-63845',
    summary: 'Snyk: fjern 4 kritiske sikkerhetssarbarheter i dev-deps',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q2-2025',
    labels: ['vedlikehold', 'sikkerhet'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-63788',
    summary: 'ESLint v9: migrer til flat config-format',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q2-2025',
    labels: ['vedlikehold', 'lint'],
    issuetype: 'Task',
  },
];

// ============================================================
// Q3 2025 — juli til september
// ============================================================

export const Q3_2025_OKR: JiraIssue[] = [
  {
    key: 'ETU-65201',
    summary: 'Ny komponent: MultiSelect – flervalgsdropdown med chips',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q3-2025',
    labels: ['okr-q3-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: 5 nye komponenter levert og dokumentert i Q3',
    issuetype: 'Story',
  },
  {
    key: 'ETU-65178',
    summary: 'Ny komponent: RatingInput – stjerne-vurdering for tilbakemeldinger',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q3-2025',
    labels: ['okr-q3-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: 5 nye komponenter levert og dokumentert i Q3',
    issuetype: 'Story',
  },
  {
    key: 'ETU-65134',
    summary: 'A11y: kontrasttest av alle token-farger mot WCAG 2.2 AA',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q3-2025',
    labels: ['okr-q3-2025', 'a11y', 'tokens', 'linje'],
    okrKobling: 'OKR: 100% WCAG 2.2 AA-sertifisering av token-paletten',
    issuetype: 'Task',
  },
  {
    key: 'ETU-65089',
    summary: 'Design token generasjon: støtte for multi-brand theming',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q3-2025',
    labels: ['okr-q3-2025', 'tokens', 'linje'],
    okrKobling: 'OKR: Reduser Figma-til-kode-tid med 50%',
    issuetype: 'Epic',
  },
  {
    key: 'ETU-65045',
    summary: 'Ny komponent: InlineAlert – inline-varsel i skjema',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q3-2025',
    labels: ['okr-q3-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: 5 nye komponenter levert og dokumentert i Q3',
    issuetype: 'Story',
  },
  {
    key: 'ETU-64998',
    summary: 'Linje-dokumentasjon: redesign av "kom-i-gang"-seksjonen',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q3-2025',
    labels: ['okr-q3-2025', 'dokumentasjon', 'linje'],
    okrKobling: 'OKR: Dokumentasjonskvalitet – NPS over 4.5 i kvartalsmaling',
    issuetype: 'Story',
  },
  {
    key: 'ETU-64952',
    summary: 'Ny komponent: Breadcrumbs – navigasjons-sti-komponent',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q3-2025',
    labels: ['okr-q3-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: 5 nye komponenter levert og dokumentert i Q3',
    issuetype: 'Story',
  },
  {
    key: 'ETU-64899',
    summary: 'Playroom: konfigurer for alle pakker med korrekte imports',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q3-2025',
    labels: ['okr-q3-2025', 'verktoy', 'linje'],
    okrKobling: 'OKR: Reduser Figma-til-kode-tid med 50%',
    issuetype: 'Task',
  },
  {
    key: 'ETU-64845',
    summary: 'Ny komponent: Avatar – profilbilde med fallback-initialer',
    status: 'Pagar',
    category: 'okr',
    kvartal: 'Q3-2025',
    labels: ['okr-q3-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: 5 nye komponenter levert og dokumentert i Q3',
    issuetype: 'Story',
  },
  {
    key: 'ETU-64798',
    summary: 'Brukerundersøkelse 2025: design og gjennomfør kvartalsmaling',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q3-2025',
    labels: ['okr-q3-2025', 'innsikt', 'linje'],
    okrKobling: 'OKR: Dokumentasjonskvalitet – NPS over 4.5 i kvartalsmaling',
    issuetype: 'Task',
  },
];

export const Q3_2025_SUPPORT: JiraIssue[] = [
  {
    key: 'ETU-65312',
    summary: 'Bug: Datepicker krasjer pa Android Chrome ved datovelging',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q3-2025',
    labels: ['support', 'bug', 'datepicker'],
    team: 'Billett & Betaling',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-65278',
    summary: 'Hjelp: oppsett av Linje i Turborepo-monorepo',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q3-2025',
    labels: ['support', 'onboarding'],
    team: 'Platform',
    issuetype: 'Support',
  },
  {
    key: 'ETU-65234',
    summary: 'Pair programming: tilpasset NavigationCard for billett-flyt',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q3-2025',
    labels: ['support', 'pair-programming'],
    team: 'Billett & Betaling',
    issuetype: 'Support',
  },
  {
    key: 'ETU-65189',
    summary: 'Bug: TravelTag viser feil ikon ved "cancelled"-status',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q3-2025',
    labels: ['support', 'bug', 'travel'],
    team: 'Sanntid',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-65145',
    summary: 'Rådgiving: animasjonsstrategi for lasting av sanntidsdata',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q3-2025',
    labels: ['support', 'radgivning'],
    team: 'Kart & Sanntid',
    issuetype: 'Support',
  },
  {
    key: 'ETU-65098',
    summary: 'Review: designsystem-bruk i ny kundeprofil-side',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q3-2025',
    labels: ['support', 'review'],
    team: 'Kundeservice',
    issuetype: 'Task',
  },
  {
    key: 'ETU-65056',
    summary: 'Spørsmål: Contrast-komponent og tredjeparts CSS-rammer',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q3-2025',
    labels: ['support', 'sporsmal'],
    team: 'Entur.no',
    issuetype: 'Support',
  },
  {
    key: 'ETU-65012',
    summary: 'Bug: ExpandablePanel nøster feil med skjermleser pa iOS',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q3-2025',
    labels: ['support', 'bug', 'expand', 'a11y'],
    team: 'Reiseplanlegging',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-64967',
    summary: 'Konsultasjon: typografi-hierarki for ny informasjonsside',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q3-2025',
    labels: ['support', 'radgivning', 'typografi'],
    team: 'Ruteplanlegging',
    issuetype: 'Support',
  },
];

export const Q3_2025_VEDLIKEHOLD: JiraIssue[] = [
  {
    key: 'ETU-65389',
    summary: 'Node.js: oppgrader til v22 LTS i alle pakker og CI',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q3-2025',
    labels: ['vedlikehold', 'infrastruktur'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-65345',
    summary: 'Gatsby 5: fikse breaking changes i Head API etter oppgradering',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q3-2025',
    labels: ['vedlikehold', 'gatsby'],
    issuetype: 'Bug',
  },
  {
    key: 'ETU-65301',
    summary: 'Fjern foreldede @types-pakker og reduser bundle-størrelse',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q3-2025',
    labels: ['vedlikehold', 'deps', 'build'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-65257',
    summary: 'Jest: migrer til v30 og oppdater snapshot-tester',
    status: 'Pagar',
    category: 'vedlikehold',
    kvartal: 'Q3-2025',
    labels: ['vedlikehold', 'test'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-65213',
    summary: 'Automatiser token-generasjon via GitHub Actions workflow',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q3-2025',
    labels: ['vedlikehold', 'ci', 'tokens'],
    issuetype: 'Task',
  },
];

// ============================================================
// Q4 2025 — oktober til desember
// ============================================================

export const Q4_2025_OKR: JiraIssue[] = [
  {
    key: 'ETU-66201',
    summary: 'Ny komponent: CommandPalette – søkebasert kommando-grensesnitt',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q4-2025',
    labels: ['okr-q4-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: 4 nye premium-komponenter levert i Q4',
    issuetype: 'Story',
  },
  {
    key: 'ETU-66156',
    summary: 'Ny komponent: DataTable – avansert tabell med sortering, filter og paginering',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q4-2025',
    labels: ['okr-q4-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: 4 nye premium-komponenter levert i Q4',
    issuetype: 'Story',
  },
  {
    key: 'ETU-66112',
    summary: 'Linje v4: planlegg og dokumenter breaking changes for 2026',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q4-2025',
    labels: ['okr-q4-2025', 'migrering', 'linje'],
    okrKobling: 'OKR: Publiser migreringsguide til v4 innen Q4',
    issuetype: 'Epic',
  },
  {
    key: 'ETU-66067',
    summary: 'A11y: full WCAG 2.2 AA-sertifisering — sluttrapport',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q4-2025',
    labels: ['okr-q4-2025', 'a11y', 'linje'],
    okrKobling: 'OKR: 100% WCAG 2.2 AA-sertifisering av token-paletten',
    issuetype: 'Task',
  },
  {
    key: 'ETU-66023',
    summary: 'Ny komponent: VirtualList – ytelsesoptimalisert lang-liste',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q4-2025',
    labels: ['okr-q4-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: 4 nye premium-komponenter levert i Q4',
    issuetype: 'Story',
  },
  {
    key: 'ETU-65978',
    summary: 'Migreringsguide v3 til v4: interaktiv sjekkliste pa dokumentasjonsside',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q4-2025',
    labels: ['okr-q4-2025', 'dokumentasjon', 'migrering', 'linje'],
    okrKobling: 'OKR: Publiser migreringsguide til v4 innen Q4',
    issuetype: 'Story',
  },
  {
    key: 'ETU-65934',
    summary: 'Ny komponent: SplitButton – knapp med dropdown-meny',
    status: 'Pagar',
    category: 'okr',
    kvartal: 'Q4-2025',
    labels: ['okr-q4-2025', 'komponent', 'linje'],
    okrKobling: 'OKR: 4 nye premium-komponenter levert i Q4',
    issuetype: 'Story',
  },
  {
    key: 'ETU-65889',
    summary: 'Kvartalsmaling Q4: brukertilfredshets-NPS for designsystemet',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q4-2025',
    labels: ['okr-q4-2025', 'innsikt', 'linje'],
    okrKobling: 'OKR: Dokumentasjonskvalitet – NPS over 4.5 i kvartalsmaling',
    issuetype: 'Task',
  },
  {
    key: 'ETU-65845',
    summary: 'Figma-bibliotek v4: rydde opp og fjerne deprecated komponenter',
    status: 'Fullfort',
    category: 'okr',
    kvartal: 'Q4-2025',
    labels: ['okr-q4-2025', 'figma', 'linje'],
    okrKobling: 'OKR: Reduser Figma-til-kode-tid med 50%',
    issuetype: 'Task',
  },
];

export const Q4_2025_SUPPORT: JiraIssue[] = [
  {
    key: 'ETU-66378',
    summary: 'Bug: Loader-spinner vises ikke riktig i Edge 120',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q4-2025',
    labels: ['support', 'bug', 'loader'],
    team: 'Platform',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-66334',
    summary: 'Pair programming: custom theme for Entur Partner-portal',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q4-2025',
    labels: ['support', 'pair-programming'],
    team: 'Entur.no',
    issuetype: 'Support',
  },
  {
    key: 'ETU-66290',
    summary: 'Hjelp: migrering av skjemaer fra v3 til v4 API',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q4-2025',
    labels: ['support', 'migrering'],
    team: 'Reiseplanlegging',
    issuetype: 'Support',
  },
  {
    key: 'ETU-66245',
    summary: 'Bug: TimePicker krasjer ved serverside-rendering i Next.js',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q4-2025',
    labels: ['support', 'bug', 'ssr'],
    team: 'Ruteplanlegging',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-66220',
    summary: 'Konsultasjon: tilgjengelig fargebruk i ny rapporteringsmodul',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q4-2025',
    labels: ['support', 'radgivning', 'a11y'],
    team: 'Innsikt',
    issuetype: 'Support',
  },
  {
    key: 'ETU-66175',
    summary: 'Review: ny onboarding-flyt – Linje-komponent-samsvar',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q4-2025',
    labels: ['support', 'review'],
    team: 'Kundeservice',
    issuetype: 'Task',
  },
  {
    key: 'ETU-66130',
    summary: 'Bug: SearchableDropdown mister fokus pa esc-tasten i Chrome',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q4-2025',
    labels: ['support', 'bug', 'dropdown'],
    team: 'Billett & Betaling',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-66085',
    summary: 'Spørsmål: beste praksis for dark mode i egendefinerte komponenter',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q4-2025',
    labels: ['support', 'sporsmal'],
    team: 'Kart & Sanntid',
    issuetype: 'Support',
  },
  {
    key: 'ETU-66040',
    summary: 'Pair programming: TravelLeg med egendefinert rutevisning',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q4-2025',
    labels: ['support', 'pair-programming'],
    team: 'Sanntid',
    issuetype: 'Support',
  },
  {
    key: 'ETU-65995',
    summary: 'Bug: Tooltip forsvinner ved museklikk pa touch-enheter',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q4-2025',
    labels: ['support', 'bug', 'tooltip'],
    team: 'Platform',
    issuetype: 'Bug',
  },
];

export const Q4_2025_VEDLIKEHOLD: JiraIssue[] = [
  {
    key: 'ETU-66456',
    summary: 'Lerna: konfigurer independent versioning for v4-utgivelse',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q4-2025',
    labels: ['vedlikehold', 'infrastruktur', 'release'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-66412',
    summary: 'Oppdater alle Peer Dependencies til React 18-kompatible versjoner',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q4-2025',
    labels: ['vedlikehold', 'deps', 'react'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-66367',
    summary: 'Fjern deprecated CSS custom properties fra v2-era',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q4-2025',
    labels: ['vedlikehold', 'css', 'tokens'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-66323',
    summary: 'CI: reduser build-tid med parallell Nx-kjøring og remote cache',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q4-2025',
    labels: ['vedlikehold', 'ci', 'performance'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-66278',
    summary: 'TypeScript 5.9: oppdater tsconfig.json i alle 23 pakker',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q4-2025',
    labels: ['vedlikehold', 'typescript'],
    issuetype: 'Task',
  },
];

// ============================================================
// Q1 2026 — januar til mars (pagar)
// ============================================================

export const Q1_2026_OKR: JiraIssue[] = [
  {
    key: 'ETU-67101',
    summary: 'Linje v4: offisiell utgivelse og migreringsstøtte for alle team',
    status: 'Pagar',
    category: 'okr',
    kvartal: 'Q1-2026',
    labels: ['okr-q1-2026', 'release', 'linje'],
    okrKobling: 'OKR: Linje v4 i produksjon hos alle konsumentteam innen Q1 2026',
    issuetype: 'Epic',
  },
  {
    key: 'ETU-67089',
    summary: 'Ny komponent: ComboBox – kombinert input og dropdown',
    status: 'Pagar',
    category: 'okr',
    kvartal: 'Q1-2026',
    labels: ['okr-q1-2026', 'komponent', 'linje'],
    okrKobling: 'OKR: 3 nye komponenter i Q1 2026',
    issuetype: 'Story',
  },
  {
    key: 'ETU-67045',
    summary: 'React 18: migrer alle komponenter til concurrent mode',
    status: 'Pagar',
    category: 'okr',
    kvartal: 'Q1-2026',
    labels: ['okr-q1-2026', 'react', 'linje'],
    okrKobling: 'OKR: Linje v4 i produksjon hos alle konsumentteam innen Q1 2026',
    issuetype: 'Epic',
  },
  {
    key: 'ETU-66998',
    summary: 'Ny komponent: SpeedDial – rask-handling-meny for mobile flater',
    status: 'IkkeStartet',
    category: 'okr',
    kvartal: 'Q1-2026',
    labels: ['okr-q1-2026', 'komponent', 'linje'],
    okrKobling: 'OKR: 3 nye komponenter i Q1 2026',
    issuetype: 'Story',
  },
  {
    key: 'ETU-66945',
    summary: 'A11y: automatisert regresjonstesting med axe-core i CI',
    status: 'Pagar',
    category: 'okr',
    kvartal: 'Q1-2026',
    labels: ['okr-q1-2026', 'a11y', 'ci', 'linje'],
    okrKobling: 'OKR: Nulltoleranse for a11y-regresjoner i 2026',
    issuetype: 'Epic',
  },
  {
    key: 'ETU-66901',
    summary: 'Ny komponent: Timeline – kronologisk hendelsesvisning',
    status: 'IkkeStartet',
    category: 'okr',
    kvartal: 'Q1-2026',
    labels: ['okr-q1-2026', 'komponent', 'linje'],
    okrKobling: 'OKR: 3 nye komponenter i Q1 2026',
    issuetype: 'Story',
  },
  {
    key: 'ETU-66856',
    summary: 'Dokumentasjon: AI-drevet søk og komponent-hjelper i docs-siden',
    status: 'Pagar',
    category: 'okr',
    kvartal: 'Q1-2026',
    labels: ['okr-q1-2026', 'dokumentasjon', 'linje'],
    okrKobling: 'OKR: Reduser tid brukt pa Slack-spørsmål med 30%',
    issuetype: 'Story',
  },
  {
    key: 'ETU-66812',
    summary: 'Figma Variables: full migrasjon fra Figma Styles til Variables',
    status: 'Pagar',
    category: 'okr',
    kvartal: 'Q1-2026',
    labels: ['okr-q1-2026', 'figma', 'tokens', 'linje'],
    okrKobling: 'OKR: Reduser Figma-til-kode-tid med 50%',
    issuetype: 'Epic',
  },
];

export const Q1_2026_SUPPORT: JiraIssue[] = [
  {
    key: 'ETU-67201',
    summary: 'Hjelp: migrering fra Linje v3 til v4 – team Billett & Betaling',
    status: 'Pagar',
    category: 'support',
    kvartal: 'Q1-2026',
    labels: ['support', 'migrering'],
    team: 'Billett & Betaling',
    issuetype: 'Support',
  },
  {
    key: 'ETU-67178',
    summary: 'Bug: DataTable mister radmarkering etter sortering',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2026',
    labels: ['support', 'bug', 'table'],
    team: 'Innsikt',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-67134',
    summary: 'Pair programming: v4-migrering av kompleks skjemaflyt',
    status: 'Pagar',
    category: 'support',
    kvartal: 'Q1-2026',
    labels: ['support', 'pair-programming', 'migrering'],
    team: 'Reiseplanlegging',
    issuetype: 'Support',
  },
  {
    key: 'ETU-67110',
    summary: 'Konsultasjon: responsiv navigasjon pa tvers av breakpoints',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2026',
    labels: ['support', 'radgivning'],
    team: 'Entur.no',
    issuetype: 'Support',
  },
  {
    key: 'ETU-67065',
    summary: 'Bug: ComboBox-forslag forsvinner ved rask skriving',
    status: 'Pagar',
    category: 'support',
    kvartal: 'Q1-2026',
    labels: ['support', 'bug', 'komponent'],
    team: 'Ruteplanlegging',
    issuetype: 'Bug',
  },
  {
    key: 'ETU-67020',
    summary: 'Review: ny kart-overlay med Linje-styled markører',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2026',
    labels: ['support', 'review'],
    team: 'Kart & Sanntid',
    issuetype: 'Task',
  },
  {
    key: 'ETU-66968',
    summary: 'Spørsmål: hvordan bruke CSS custom properties med SSR',
    status: 'Fullfort',
    category: 'support',
    kvartal: 'Q1-2026',
    labels: ['support', 'sporsmal', 'ssr'],
    team: 'Platform',
    issuetype: 'Support',
  },
  {
    key: 'ETU-66922',
    summary: 'Hjelp: oppsett av Linje i ny Micro-frontend-arkitektur',
    status: 'Pagar',
    category: 'support',
    kvartal: 'Q1-2026',
    labels: ['support', 'onboarding', 'arkitektur'],
    team: 'Platform',
    issuetype: 'Support',
  },
];

export const Q1_2026_VEDLIKEHOLD: JiraIssue[] = [
  {
    key: 'ETU-67312',
    summary: 'Publiser @entur/* v4.0.0 til npm-registeret',
    status: 'Pagar',
    category: 'vedlikehold',
    kvartal: 'Q1-2026',
    labels: ['vedlikehold', 'release', 'infrastruktur'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-67278',
    summary: 'Changelog: generer CHANGELOG.md for alle pakker for v4',
    status: 'Pagar',
    category: 'vedlikehold',
    kvartal: 'Q1-2026',
    labels: ['vedlikehold', 'release', 'docs'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-67234',
    summary: 'Rydd opp deprecated exports og fjern fra barrel-filer',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q1-2026',
    labels: ['vedlikehold', 'refaktorering'],
    issuetype: 'Task',
  },
  {
    key: 'ETU-67189',
    summary: 'Gatsby: oppgrader til v5.14 og fikse head-API-advarsel',
    status: 'Fullfort',
    category: 'vedlikehold',
    kvartal: 'Q1-2026',
    labels: ['vedlikehold', 'gatsby', 'docs'],
    issuetype: 'Bug',
  },
];

// ============================================================
// Samlede lister (brukt av tabeller)
// ============================================================

export const OKR_ISSUES: JiraIssue[] = [
  ...Q1_2025_OKR,
  ...Q2_2025_OKR,
  ...Q3_2025_OKR,
  ...Q4_2025_OKR,
  ...Q1_2026_OKR,
];

export const SUPPORT_ISSUES: JiraIssue[] = [
  ...Q1_2025_SUPPORT,
  ...Q2_2025_SUPPORT,
  ...Q3_2025_SUPPORT,
  ...Q4_2025_SUPPORT,
  ...Q1_2026_SUPPORT,
];

export const VEDLIKEHOLD_ISSUES: JiraIssue[] = [
  ...Q1_2025_VEDLIKEHOLD,
  ...Q2_2025_VEDLIKEHOLD,
  ...Q3_2025_VEDLIKEHOLD,
  ...Q4_2025_VEDLIKEHOLD,
  ...Q1_2026_VEDLIKEHOLD,
];

// ============================================================
// Aggregerte statistikker — samlet og per kvartal
// ============================================================

const statsFor = (issues: JiraIssue[]) => ({
  total: issues.length,
  fullfort: issues.filter(i => i.status === 'Fullfort').length,
  pagar: issues.filter(i => i.status === 'Pagar').length,
  ikkeStartet: issues.filter(i => i.status === 'IkkeStartet').length,
});

export const OKR_STATS = statsFor(OKR_ISSUES);
export const SUPPORT_STATS = statsFor(SUPPORT_ISSUES);
export const VEDLIKEHOLD_STATS = statsFor(VEDLIKEHOLD_ISSUES);

export const TOTAL_ISSUES =
  OKR_STATS.total + SUPPORT_STATS.total + VEDLIKEHOLD_STATS.total;

// Per-kvartal-statistikker
export type KvartalStats = {
  kvartal: Kvartal;
  label: string;
  okr: number;
  support: number;
  vedlikehold: number;
  total: number;
};

const allIssues = [...OKR_ISSUES, ...SUPPORT_ISSUES, ...VEDLIKEHOLD_ISSUES];

const kvartalStatsFor = (k: Kvartal, label: string): KvartalStats => {
  const issues = allIssues.filter(i => i.kvartal === k);
  return {
    kvartal: k,
    label,
    okr: issues.filter(i => i.category === 'okr').length,
    support: issues.filter(i => i.category === 'support').length,
    vedlikehold: issues.filter(i => i.category === 'vedlikehold').length,
    total: issues.length,
  };
};

export const KVARTAL_STATS: KvartalStats[] = [
  kvartalStatsFor('Q1-2025', 'Q1 2025'),
  kvartalStatsFor('Q2-2025', 'Q2 2025'),
  kvartalStatsFor('Q3-2025', 'Q3 2025'),
  kvartalStatsFor('Q4-2025', 'Q4 2025'),
  kvartalStatsFor('Q1-2026', 'Q1 2026'),
];

// OKR-mal-oversikt (samlet pa tvers av kvartal)
export const OKR_MAAL = [
  {
    tittel: 'Nye komponenter',
    fullLabel: 'Nye komponenter levert og dokumentert',
    antall: OKR_ISSUES.filter(i => i.okrKobling?.includes('komponent')).length,
    color: '#64b2fb',
  },
  {
    tittel: 'Universell utforming',
    fullLabel: 'Universell utforming og WCAG 2.2 AA',
    antall: OKR_ISSUES.filter(
      i => i.okrKobling?.includes('Universell') || i.okrKobling?.includes('WCAG') || i.okrKobling?.includes('a11y'),
    ).length,
    color: '#7bc00b',
  },
  {
    tittel: 'Figma-til-kode',
    fullLabel: 'Reduser Figma-til-kode-tid med 50%',
    antall: OKR_ISSUES.filter(i => i.okrKobling?.includes('Figma-til-kode')).length,
    color: '#ffbf9e',
  },
  {
    tittel: 'Onboarding og migrering',
    fullLabel: 'Onboarding, migrering og v4-lansering',
    antall: OKR_ISSUES.filter(
      i => i.okrKobling?.includes('onboarding') || i.okrKobling?.includes('v4') || i.okrKobling?.includes('migrering'),
    ).length,
    color: '#ff9494',
  },
  {
    tittel: 'Dokumentasjonskvalitet',
    fullLabel: 'Dokumentasjonskvalitet og NPS',
    antall: OKR_ISSUES.filter(i => i.okrKobling?.includes('NPS') || i.okrKobling?.includes('Dokumentasjon') || i.okrKobling?.includes('Reduser tid')).length,
    color: '#c4b5fd',
  },
];

// Støtte-team fordeling
export const SUPPORT_TEAMS = [
  {
    team: 'Platform',
    antall: SUPPORT_ISSUES.filter(i => i.team === 'Platform').length,
    color: '#64b2fb',
  },
  {
    team: 'Billett & Betaling',
    antall: SUPPORT_ISSUES.filter(i => i.team === 'Billett & Betaling').length,
    color: '#7bc00b',
  },
  {
    team: 'Reiseplanlegging',
    antall: SUPPORT_ISSUES.filter(i => i.team === 'Reiseplanlegging').length,
    color: '#ffbf9e',
  },
  {
    team: 'Kart & Sanntid',
    antall: SUPPORT_ISSUES.filter(i => i.team === 'Kart & Sanntid').length,
    color: '#ff9494',
  },
  {
    team: 'Sanntid',
    antall: SUPPORT_ISSUES.filter(i => i.team === 'Sanntid').length,
    color: '#c4b5fd',
  },
  {
    team: 'Entur.no',
    antall: SUPPORT_ISSUES.filter(i => i.team === 'Entur.no').length,
    color: '#fcd34d',
  },
  {
    team: 'Kundeservice',
    antall: SUPPORT_ISSUES.filter(i => i.team === 'Kundeservice').length,
    color: '#6ee7b7',
  },
  {
    team: 'Innsikt',
    antall: SUPPORT_ISSUES.filter(i => i.team === 'Innsikt').length,
    color: '#f9a8d4',
  },
  {
    team: 'Ruteplanlegging',
    antall: SUPPORT_ISSUES.filter(i => i.team === 'Ruteplanlegging').length,
    color: '#fb923c',
  },
].filter(t => t.antall > 0).sort((a, b) => b.antall - a.antall);

// Støtte-type fordeling
export const SUPPORT_TYPER = [
  {
    type: 'Bug-fix',
    antall: SUPPORT_ISSUES.filter(i => i.labels.includes('bug')).length,
    color: '#ff9494',
  },
  {
    type: 'Rådgiving / Konsultasjon',
    antall: SUPPORT_ISSUES.filter(i => i.labels.includes('radgivning')).length,
    color: '#64b2fb',
  },
  {
    type: 'Pair programming',
    antall: SUPPORT_ISSUES.filter(i => i.labels.includes('pair-programming')).length,
    color: '#7bc00b',
  },
  {
    type: 'Migrering',
    antall: SUPPORT_ISSUES.filter(i => i.labels.includes('migrering')).length,
    color: '#ffbf9e',
  },
  {
    type: 'Spørsmål / Slack-hjelp',
    antall: SUPPORT_ISSUES.filter(i => i.labels.includes('sporsmal')).length,
    color: '#c4b5fd',
  },
  {
    type: 'Design review',
    antall: SUPPORT_ISSUES.filter(i => i.labels.includes('review')).length,
    color: '#fcd34d',
  },
  {
    type: 'Onboarding',
    antall: SUPPORT_ISSUES.filter(i => i.labels.includes('onboarding')).length,
    color: '#6ee7b7',
  },
];

// Seksjons-navigasjon
export const OKR_SECTION_NAV = [
  { id: 'sammendrag', label: 'Sammendrag' },
  { id: 'per-kvartal', label: 'Per kvartal' },
  { id: 'okr-arbeid', label: 'OKR-arbeid' },
  { id: 'support', label: 'Støtte og bistand' },
  { id: 'vedlikehold', label: 'Vedlikehold' },
  { id: 'issues-tabell', label: 'Issues-tabell' },
];
