import formSnippets from './FormSnippets';
// import layoutSnippets from './layoutSnippets';
import templateSnippets from './TemplateSnippets';
import autoSnippets from './SnippetsAutogenerated';

const snippets = [
  ...templateSnippets,
  ...formSnippets,
  //   ...layoutSnippets,
  ...autoSnippets,
];

export default snippets;
