aliases:
  - &ssh-fingerprint
    fingerprints:
      - '02:85:42:40:c5:08:04:66:58:80:10:2f:60:97:38:c2'
  - &filter-only-master
    branches:
      only:
        - master
  - &filter-ignore-master
    branches:
      ignore:
        - master
version: 2
jobs:
  build-test-and-deploy-to-preview:
    parallelism: 1
    resource_class: xlarge
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}
            - yarn-v1-
      - restore_cache:
          name: Restore Docz/Gatsby Cache
          keys:
            - v09-docz-cache-{{ .Branch }}
            - v09-docz-cache-

      - add_ssh_keys: *ssh-fingerprint

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: build packages
          command: yarn build:packages
      - run:
          name: linter and test
          command: yarn test --runInBand && yarn lint
      - run:
          name: build documentation
          command: yarn build:documentation --scripts-prepend-node-path
      - save_cache:
          name: Save Docz/Gatsby Cache
          key: v09-docz-cache-{{ .Branch }}-{{ epoch }}
          paths:
            - .docz/.cache
            - .docz/public
      - run:
          name: Save token to a file
          command: echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/serviceaccount.preview.json
      - run:
          name: Deploy to preview channel
          command: GOOGLE_APPLICATION_CREDENTIALS=/tmp/serviceaccount.preview.json yarn deploy-docs:preview $CIRCLE_BRANCH --project=entur-design-system

  build-and-deploy-to-production:
    parallelism: 1
    resource_class: xlarge
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}
            - yarn-v1-
      - restore_cache:
          name: Restore Docz/Gatsby Cache
          keys:
            - v09-docz-cache-{{ .Branch }}
            - v09-docz-cache-

      - add_ssh_keys: *ssh-fingerprint

      - run:
          name: Save token to a file
          command: echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/serviceaccount.prod.json

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Deploy to production
          command: GOOGLE_APPLICATION_CREDENTIALS=/tmp/serviceaccount.prod.json yarn deploy-docs --project=entur-design-system
      - save_cache:
          name: Save Docz/Gatsby Cache
          key: v09-docz-cache-{{ .Branch }}-{{ epoch }}
          paths:
            - .docz/.cache
            - .docz/public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-test-and-deploy-to-preview:
          filters: *filter-ignore-master
      - build-and-deploy-to-production:
          filters: *filter-only-master
