aliases:
  - &ssh-fingerprint
    fingerprints:
      - '02:85:42:40:c5:08:04:66:58:80:10:2f:60:97:38:c2'
  - &filter-only-master
    branches:
      only:
        - master
  - &filter-ignore-master
    branches:
      ignore:
        - master

version: 2
jobs:
  build-packages:
    working_directory: ~/project
    resource_class: xlarge
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v2_3-yarn-cache-{{ checksum "yarn.lock" }}
            - v2_3-yarn-cache-

      - add_ssh_keys: *ssh-fingerprint

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

      - run:
          name: Print directory and contetn
          command: pwd && ls -la

      - save_cache:
          name: Save Yarn Package Cache
          key: v2_3-yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - apps/documentation/node_modules
            - apps/code-playground/node_modules
            - packages/icons/node_modules
            - packages/a11y/node_modules
            - packages/grid/node_modules
            - packages/tab/node_modules
            - packages/typography/node_modules
            - packages/layout/node_modules
            - packages/loader/node_modules
            - packages/expand/node_modules
            - packages/button/node_modules
            - packages/alert/node_modules
            - packages/menu/node_modules
            - packages/fileupload/node_modules
            - packages/modal/node_modules
            - packages/tooltip/node_modules
            - packages/form/node_modules
            - packages/chip/node_modules
            - packages/datepicker/node_modules
            - packages/travel/node_modules
            - packages/table/node_modules
            - packages/dropdown/node_modules
            - packages/utils/node_modules
            - packages/tokens/node_modules

      - run:
          name: build packages
          command: yarn build:packages

      - persist_to_workspace:
          root: ~/
          paths:
            - 'project/packages/*/dist'
            - 'project/packages/*/node_modules'
            - 'project/node_modules'

  lint:
    working_directory: ~/project
    resource_class: xlarge
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout

      - attach_workspace:
          at: ~/

      - run:
          name: lint code
          command: yarn lint

  test:
    working_directory: ~/project
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout

      - attach_workspace:
          at: ~/

      - run:
          name: test code
          command: yarn test --runInBand

  build-documentation:
    working_directory: ~/project
    resource_class: xlarge
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout

      - attach_workspace:
          at: ~/

      - run:
          name: build documentation site
          command: yarn cleanDocz && yarn build:documentation

      - persist_to_workspace:
          root: ~/
          paths:
            - 'project/apps/documentation/dist'

  deploy-documentation-to-preview-channel:
    working_directory: ~/project
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout

      - attach_workspace:
          at: ~/

      - run:
          name: Save token to a file
          command: echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/serviceaccount.preview.json

      - run:
          name: Deploy to preview channel
          command: GOOGLE_APPLICATION_CREDENTIALS=/tmp/serviceaccount.preview.json yarn deploy-docs:preview -- $CIRCLE_BRANCH --project=entur-design-system

  deploy-documentation-to-production:
    working_directory: ~/project
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout

      - attach_workspace:
          at: ~/

      - run:
          name: Save token to a file
          command: echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/serviceaccount.prod.json

      - run:
          name: Deploy to production
          command: GOOGLE_APPLICATION_CREDENTIALS=/tmp/serviceaccount.prod.json yarn deploy-docs -- --project=entur-design-system

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build-packages
      - lint:
          filters: *filter-ignore-master
          requires:
            - build-packages
      - test:
          filters: *filter-ignore-master
          requires:
            - build-packages
      - build-documentation:
          requires:
            - build-packages
      - Approve-to-deploy:
          filters: *filter-ignore-master
          type: approval
          requires:
            - lint
            - test
            - build-documentation
      - deploy-documentation-to-preview-channel:
          filters: *filter-ignore-master
          requires:
            - Approve-to-deploy
      - deploy-documentation-to-production:
          filters: *filter-only-master
          requires:
            - build-documentation
