aliases:
  - &ssh-fingerprint
    fingerprints:
      - '02:85:42:40:c5:08:04:66:58:80:10:2f:60:97:38:c2'
version: 2
jobs:
  build:
    parallelism: 1
    resource_class: large
    docker:
      - image: circleci/node:lts
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-v1-{{ .Branch }}-
            - yarn-v1-

      - add_ssh_keys: *ssh-fingerprint

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: build
          command: yarn build

      - run:
          name: test
          command: yarn test
  deploy:
    parallelism: 1
    resource_class: large
    docker:
      - image: circleci/node:lts
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-v1-{{ .Branch }}-
            - yarn-v1-

      - add_ssh_keys: *ssh-fingerprint

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Deploy to production
          command: yarn deploy-docs --token=$FIREBASE_TOKEN --non-interactive
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
