/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const AdjustmentsIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8.573 4.175a2 2 0 013.73 0H15v1.51h-2.723a2 2 0 01-3.68 0H1v-1.51h7.573zM7.397 10.3H15v1.51H7.432a2 2 0 01-3.74 0H1v-1.51h2.728a2 2 0 013.669 0z"
    />
  </svg>
);
export default AdjustmentsIcon;
