/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const AgreesIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14 15H2c-.6 0-1-.4-1-1V2c0-.6.4-1 1-1h7v2H3v10h10V8h2v6c0 .6-.4 1-1 1zm2-12.6L8.7 9.7l-.7.664-.7-.664-2.696-2.696 1.398-1.402L8 7.6 14.6 1 16 2.4z"
    />
  </svg>
);
export default AgreesIcon;
