/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const AlignCenterIcon: React.FC<IconProps> = ({
  className,
  ...rest
}) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M1 2h14v1.714H1V2zm2.625 3.429h8.75v1.714h-8.75V5.429zM1 8.857h14v1.714H1V8.857zm2.625 3.429h8.75V14h-8.75v-1.714z"
    />
  </svg>
);
export default AlignCenterIcon;
