/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const AlignRightIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    enable-background="new 0 0 16 16"
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M1 2h14v1.714H1V2zm5.25 3.429H15v1.714H6.25V5.429zM1 8.857h14v1.714H1V8.857zm5.25 3.429H15V14H6.25v-1.714z"
    />
    <defs>
      <filter id="a" filterUnits="userSpaceOnUse">
        <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
      </filter>
    </defs>
    <mask id="b" maskUnits="userSpaceOnUse">
      <g filter="url(#a)">
        <path
          fill="#FFF"
          d="M1 2h14v1.714H1V2zm5.25 3.429H15v1.714H6.25V5.429zM1 8.857h14v1.714H1V8.857zm5.25 3.429H15V14H6.25v-1.714z"
        />
      </g>
    </mask>
  </svg>
);
export default AlignRightIcon;
