/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const AlignLeftIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M1 2h14v1.714H1V2zm0 3.429h8.75v1.714H1V5.429zm0 3.428h14v1.714H1V8.857zm0 3.429h8.75V14H1v-1.714z"
    />
  </svg>
);
export default AlignLeftIcon;
