/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const AttachmentIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M5.5 5.375v3.5C5.5 10.362 6.583 11.5 8 11.5s2.5-1.138 2.5-2.625V4.937C10.5 2.75 8.833 1 6.75 1S3 2.75 3 4.937V9.75C3 12.637 5.25 15 8 15s5-2.363 5-5.25V4.5h-1.667v5.25c0 1.925-1.5 3.5-3.333 3.5s-3.333-1.575-3.333-3.5V4.937c0-1.225.916-2.187 2.083-2.187s2.083.962 2.083 2.187v3.938c0 .525-.333.875-.833.875s-.833-.35-.833-.875v-3.5H5.5z"
    />
  </svg>
);
export default AttachmentIcon;
