/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const BackArrowIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M6.863 14l1.224-1.254-3.762-3.85H15V7.104H4.325l3.762-3.85L6.863 2 1 8z"
    />
  </svg>
);
export default BackArrowIcon;
