/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const BackIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M6.863 14l1.224-1.254-3.762-3.85H15V7.104H4.325l3.762-3.85L6.863 2 1 8z"
    />
  </svg>
);
export default BackIcon;
