/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const BanknoteIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.125 3H1.875C1.35 3 1 3.333 1 3.833v8.334c0 .5.35.833.875.833h12.25c.525 0 .875-.333.875-.833V3.833c0-.5-.35-.833-.875-.833zm-3.412 8.333H5.288c-.35-1.166-1.313-2.083-2.538-2.416V7.083c1.225-.333 2.188-1.25 2.538-2.416H10.8c.35 1.166 1.313 2.083 2.538 2.416V9c-1.313.25-2.275 1.167-2.625 2.333zM8 6.333c-.967 0-1.75.746-1.75 1.667 0 .92.783 1.667 1.75 1.667S9.75 8.92 9.75 8c0-.92-.783-1.667-1.75-1.667z"
    />
  </svg>
);
export default BanknoteIcon;
