/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const BanknoteMultiIcon: IconComponentType = ({
  className,
  ...rest
}) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.125 4.5H1.875C1.35 4.5 1 4.833 1 5.333v8.334c0 .5.35.833.875.833h12.25c.525 0 .875-.333.875-.833V5.333c0-.5-.35-.833-.875-.833zM10.713 13H5.288a3.701 3.701 0 00-2.538-2.538V8.537A3.701 3.701 0 005.288 6H10.8a3.701 3.701 0 002.538 2.537v2.013c-1.313.262-2.275 1.225-2.625 2.45zM8 7.75a1.75 1.75 0 10-.001 3.499A1.75 1.75 0 008 7.75zM2.75 1h10.5v1.75H2.75V1z"
    />
  </svg>
);
export default BanknoteMultiIcon;
