/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const BellIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M10.537 13.162c-.962.088-1.75.088-2.537.088s-1.575 0-2.538-.088C5.813 14.212 6.776 15 8 15s2.188-.788 2.537-1.838M13.6 7.825c-.7-.613-1.225-.963-1.225-1.575v-.875C12.375 2.925 10.45 1 8 1S3.625 2.925 3.625 5.375v.875c0 .612-.525.962-1.225 1.575C1.7 8.35 1 8.875 1 9.75c0 2.45 5.338 2.625 7 2.625s7-.175 7-2.625c0-.875-.7-1.4-1.4-1.925"
    />
  </svg>
);
export default BellIcon;
