/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const BicycleIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M10.51 3.97a.453.453 0 00-.432-.324h-2.14v.7h1.95l.01.035.625 2.12-4.528.503-.357-.629h.313a.375.375 0 000-.75h-1.6a.375.375 0 000 .75h.482l.523.92-1.971 3.803a.349.349 0 00.62.32l1.761-3.4 1.505 2.65.608-.344-1.508-2.657 3.708-.412L8 10.479l.589.38 2.208-3.428 1.143 3.877a.35.35 0 10.67-.198l-2.1-7.14z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M7.977 10.65a.35.35 0 110 .7.35.35 0 010-.7m0-.65a1 1 0 100 2 1 1 0 000-2z"
    />
    <path
      fill="currentColor"
      d="M12.327 9.45c1.048 0 1.9.852 1.9 1.9s-.852 1.9-1.9 1.9-1.9-.852-1.9-1.9.852-1.9 1.9-1.9m0-.75a2.65 2.65 0 100 5.3 2.65 2.65 0 000-5.3z"
    />
    <path
      fill="currentColor"
      d="M3.627 9.45c1.048 0 1.9.852 1.9 1.9s-.852 1.9-1.9 1.9-1.9-.852-1.9-1.9.852-1.9 1.9-1.9m0-.75a2.65 2.65 0 100 5.3 2.65 2.65 0 000-5.3z"
    />
  </svg>
);
export default BicycleIcon;
