/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const BoldIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M9 13H7V9h2a2 2 0 110 4zM7 3h1a2 2 0 110 4H7V3zm4.561 4.316a3.483 3.483 0 001.418-3.207C12.781 2.305 11.143 1 9.33 1H2v1l1.447.724A.998.998 0 014 3.618v8.764a.998.998 0 01-.553.894L2 14v1h7.823c2.103 0 3.98-1.548 4.161-3.643a4.002 4.002 0 00-2.423-4.041z"
    />
  </svg>
);
export default BoldIcon;
