/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const BulletListIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M2.75 1a1.75 1.75 0 11.001 3.499A1.75 1.75 0 012.75 1zm0 5.25a1.75 1.75 0 11.001 3.499A1.75 1.75 0 012.75 6.25zm3.5-4.375H15v1.75H6.25v-1.75zm0 5.25H15v1.75H6.25v-1.75zM2.75 11.5a1.75 1.75 0 11.001 3.499A1.75 1.75 0 012.75 11.5zm3.5.875H15v1.75H6.25v-1.75z"
    />
  </svg>
);
export default BulletListIcon;
