/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const BusIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <g fill="#DD5415" fillRule="evenodd" clipRule="evenodd">
      <path d="M10.5 11.8a1 1 0 111.998.003A1 1 0 0110.5 11.8z" />
      <path d="M14.996 9.595l-.7-4.296A.353.353 0 0013.95 5H1.7c-.35 0-.7.358-.7.717V10.642c0 .178.128.358.3.358h1.547c.236-.719.906-1.2 1.703-1.2s1.468.481 1.703 1.2h3.544c.236-.719.906-1.2 1.703-1.2s1.467.481 1.703 1.2h1.447c.193 0 .35-.161.35-.358v-.988c0-.02-.002-.04-.004-.06zm-2.84-2.805c0-.198.158-.358.35-.358h1.087a.35.35 0 01.347.311l.185 1.432a.36.36 0 01-.085.282.343.343 0 01-.262.122h-1.272a.354.354 0 01-.35-.358V6.79zm-4.2 0c0-.198.157-.358.35-.358h2.8c.193 0 .35.16.35.358V8.22a.354.354 0 01-.35.358h-2.8a.354.354 0 01-.35-.358V6.79zm-4.2 0c0-.198.157-.358.35-.358h2.8c.194 0 .351.16.351.358V8.22a.355.355 0 01-.35.358h-2.8a.354.354 0 01-.35-.358V6.79zm-2.1 0c0-.198.158-.358.35-.358h.701c.193 0 .349.16.349.358V8.22a.353.353 0 01-.349.358h-.7a.354.354 0 01-.35-.358V6.79z" />
      <path d="M3.55 11.8c0-.551.449-1 1-1s1 .449 1 1a1 1 0 01-2 0z" />
    </g>
  </svg>
);
export default BusIcon;
