/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const BusShelterIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 11.187c.89 0 1.697-.337 2.307-.884 1.006.322 1.693 1.06 1.693 2.009V14H4v-1.688c0-.949.688-1.687 1.694-2.01.61.548 1.418.885 2.306.885zM5.714 7.25C5.714 6.01 6.741 5 8 5c1.262 0 2.287 1.01 2.287 2.25v.563c0 1.24-1.025 2.25-2.287 2.25-1.26 0-2.286-1.01-2.286-2.25v-.564zM14 5.1L8 2.7 2 5.1V3.808l5.555-2.223c.285-.114.605-.114.89 0L14 3.808V5.1z"
    />
  </svg>
);
export default BusShelterIcon;
