/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const CablewayIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <g fill="#78469A" fillRule="evenodd" clipRule="evenodd">
      <path d="M12.062 7.273a.35.35 0 00-.341-.272H4.279a.35.35 0 00-.341.272l-.929 4.108a.451.451 0 00.074.351l.812 1.123a.35.35 0 00.283.145h7.644a.35.35 0 00.283-.145l.812-1.123a.451.451 0 00.074-.35l-.929-4.109zm-6.233 2.892a.35.35 0 01-.35.35h-1.05a.35.35 0 01-.342-.425l.31-1.4a.35.35 0 01.34-.276h.742a.35.35 0 01.35.35v1.4zm3.643 0a.35.35 0 01-.35.35h-2.1a.35.35 0 01-.35-.35v-1.4a.35.35 0 01.35-.35h2.1a.35.35 0 01.35.35v1.4zm2.372.22a.35.35 0 01-.273.131h-1.05a.35.35 0 01-.35-.35V8.764a.35.35 0 01.35-.35h.741a.35.35 0 01.342.275l.309 1.4a.35.35 0 01-.069.295z" />
      <path d="M8 2.4a.6.6 0 11-.001 1.202A.6.6 0 018 2.4z" />
      <path d="M8.98 3.1l3.176-.797-.164-.651-3.164.795c.13.193.175.424.153.653z" />
      <path d="M7.02 2.9L3.844 3.7l.164.65 3.164-.794A.993.993 0 017.02 2.9z" />
      <path d="M8.336 5.33V3.933C8.23 3.97 8.119 4 8 4s-.23-.03-.336-.068V5.33H6.505v.671h2.99v-.67h-1.16z" />
    </g>
  </svg>
);
export default CablewayIcon;
