/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const CarIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M14.002 7.2H14l-1.092-3.337C12.74 3.35 12.223 3 11.636 3H4.368c-.587 0-1.104.35-1.272.862L2 7.2h-.002A.998.998 0 001 8.198v3.503c0 .276.223.499.499.499H2v.667a1.1 1.1 0 002.2 0V12.2h7.6v.667a1.1 1.1 0 002.2 0V12.2h.501a.499.499 0 00.499-.499V8.198a.998.998 0 00-.998-.998zM3.27 7.133l.84-2.739a.51.51 0 01.495-.344h6.79c.23 0 .431.14.494.344l.84 2.74c.01.033-.016.066-.054.066h-9.35c-.038 0-.065-.033-.055-.067zM2.8 8.2c.44.002.799.36.8.804a.8.8 0 11-.8-.804zm10.4 1.6a.8.8 0 110-1.6.8.8 0 010 1.6z"
      clipRule="evenodd"
    />
  </svg>
);
export default CarIcon;
