/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ChatIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.15 4.733c.469 0 .85.384.85.856v5.989a.854.854 0 01-.85.855h-1.702V15l-2.553-2.567H5.641l1.555-1.71h5.252c.47 0 .85-.384.85-.856V4.733h.851zM1.85 1h8.51c.469 0 .85.383.85.856v5.988a.854.854 0 01-.85.856H6.104l-2.553 2.567V8.7H1.851A.854.854 0 011 7.844V1.856C1 1.383 1.381 1 1.85 1z"
    />
  </svg>
);
export default ChatIcon;
