/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const CheckIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M13.763 3l-7.76 7.772-3.765-3.773L1 8.239l3.766 3.771 1.237 1.24 8.998-9.011z"
    />
  </svg>
);
export default CheckIcon;
