/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ClockIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 1C4.15 1 1 4.15 1 8s3.15 7 7 7 7-3.15 7-7-3.15-7-7-7m0 12.25c-2.888 0-5.25-2.363-5.25-5.25S5.112 2.75 8 2.75 13.25 5.112 13.25 8 10.887 13.25 8 13.25m.875-8.75h-1.75v4.375H11.5v-1.75H8.875V4.5z"
    />
  </svg>
);
export default ClockIcon;
