/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const CloseIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 9.28L2.28 15 1 13.72 6.72 8 1 2.28 2.28 1 8 6.72 13.72 1 15 2.28 9.28 8 15 13.72 13.72 15 8 9.28z"
    />
  </svg>
);
export default CloseIcon;
