/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const CoffeeIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M1 5.374v3.063c0 2.012 1.049 3.762 2.625 4.812h-1.75c-.525 0-.875.349-.875.875s.35.875.875.875H13.25c.525 0 .875-.349.875-.875s-.35-.875-.875-.875h-3.5a5.57 5.57 0 001.75-1.75h.875c1.487 0 2.625-1.138 2.625-2.625V6.249c0-.525-.35-.875-.875-.875H1zm11.375 3.063V7.124h.875v1.75c0 .525-.35.875-.875.875H12.2c.088-.437.175-.875.175-1.312zm-3.5-4.813V1h1.75v2.624h-1.75zm-3.5 0V1h1.75v2.624h-1.75zm-3.5 0V1h1.75v2.624h-1.75z"
    />
  </svg>
);
export default CoffeeIcon;
