/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const CollapsedIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M7.4 7.2l-5-4 1.2-1.6L8 5.1l4.4-3.5 1.2 1.6-5 4c-.3.3-.9.3-1.2 0zm.6 3.7l-4.4 3.5-1.2-1.6 5-4c.2-.1.4-.2.6-.2s.4.1.6.2l5 4-1.2 1.6L8 10.9z"
    />
  </svg>
);
export default CollapsedIcon;
