/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ColorIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M2 12.2h12V15H2v-2.8zm4.918-6.958l.846-2.545h.473l.846 2.545H6.918zm4.955 3.432L9.456 1H6.545L4.128 8.674a.848.848 0 01-.5.534l-.705.277v.848h4.23v-.848L5.79 9.06l.563-2.122h3.294l.564 2.122-1.365.424v.848h4.23v-.848l-.705-.277a.848.848 0 01-.498-.534z"
    />
  </svg>
);
export default ColorIcon;
