/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ColorIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M11.505 9.238c-.963 0-1.75-.78-1.75-1.732 0-.953.787-1.732 1.75-1.732s1.751.78 1.751 1.732-.788 1.732-1.75 1.732M8.878 12.7c-.525 0-.876-.346-.876-.866s.35-.866.876-.866c.525 0 .875.347.875.866 0 .52-.35.866-.875.866M5.377 10.97c-.525 0-.875-.346-.875-.866s.35-.865.875-.865.876.346.876.865c0 .52-.35.866-.876.866m-1.75-3.463c-.526 0-.876-.347-.876-.866s.35-.866.875-.866.876.346.876.866-.35.866-.876.866m9.542-3.637c-3.151-1.472-5.777 1.559-7.003 0-.438-.606.613-1.732 0-2.511-.438-.52-1.488-.433-2.101 0C2.226 2.657 1 4.735 1 7.073 1 10.883 4.152 14 8.003 14c3.24 0 5.953-2.165 6.741-5.109.35-.952.7-3.896-1.576-5.022"
    />
  </svg>
);
export default ColorIcon;
