/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const CompanyIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.125 8.875h-1.75v-5.25c0-.525-.35-.875-.875-.875H8.875V1h-1.75v1.75H4.5c-.525 0-.875.35-.875.875v5.25h-1.75c-.525 0-.875.35-.875.875v4.375c0 .525.35.875.875.875h12.25c.525 0 .875-.35.875-.875V9.75c0-.525-.35-.875-.875-.875zm-8.75.875V4.5h5.25v8.75h-1.75v-2.625h-1.75v2.625h-1.75v-3.5z"
    />
  </svg>
);
export default CompanyIcon;
