/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ConfigurationIcon: IconComponentType = ({
  className,
  ...rest
}) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M12.554 5.53l-2.096-2.09 2.096-2.091C12.117 1.087 11.594 1 11.07 1a3.91 3.91 0 00-3.93 3.92c0 .436.087.785.174 1.22l-5.765 4.27C.85 10.933.85 11.89 1.374 12.5l2.009 2.091c.611.61 1.572.523 2.096-.174l4.28-5.75c.437.086.874.174 1.31.174A3.91 3.91 0 0015 4.92a4.06 4.06 0 00-.262-1.481l-2.184 2.09z"
    />
  </svg>
);
export default ConfigurationIcon;
