/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ContactsIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M4.5 9.75S5.375 8 8 8s3.5 1.75 3.5 1.75h-7zm3.5-7a1.75 1.75 0 11.001 3.499A1.75 1.75 0 018 2.75zM14.125 1H1.875A.875.875 0 001 1.875V11.5c0 .483.392.875.875.875h3.138l2.368 2.369a.873.873 0 001.238 0l2.368-2.369h3.138A.875.875 0 0015 11.5V1.875A.875.875 0 0014.125 1z"
    />
  </svg>
);
export default ContactsIcon;
