/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const CutleryIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M7.25 1h.875v5.25c0 .962-.788 1.75-1.75 1.75v5.688c0 .7-.612 1.312-1.313 1.312-.7 0-1.312-.612-1.312-1.312V8C2.788 8 2 7.212 2 6.25V1h.875v3.5h1.75V1H5.5v3.5h1.75V1zm7 0v12.688c0 .7-.612 1.312-1.313 1.312-.7 0-1.312-.612-1.312-1.312v-3.063h-1.75v-5.25A4.333 4.333 0 0114.25 1z"
    />
  </svg>
);
export default CutleryIcon;
