/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const DeleteIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M5.375 7.125h1.75v5.25h-1.75v-5.25zm3.5 0h1.75v5.25h-1.75v-5.25zm2.625-5.25c0-.525-.35-.875-.875-.875h-5.25c-.525 0-.875.35-.875.875v1.75H1v1.75h.875v8.75c0 .525.35.875.875.875h10.5c.525 0 .875-.35.875-.875v-8.75H15v-1.75h-3.5v-1.75zm-5.25.875h3.5v.875h-3.5V2.75zm6.125 2.625v7.875h-8.75V5.375h8.75z"
    />
  </svg>
);
export default DeleteIcon;
