/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const DepositionIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M15 4.5v1.75h-1.4l1.05 2.8c.525 1.312.35 2.8-.438 4.025C13.425 14.3 12.026 15 10.626 15H5.287c-1.4 0-2.712-.7-3.5-1.925S.825 10.362 1.35 9.05l1.05-2.8H1V4.5h14zM5.812 1a1.313 1.313 0 110 2.626 1.313 1.313 0 010-2.626zm4.375 0a1.313 1.313 0 110 2.626 1.313 1.313 0 010-2.626z"
    />
  </svg>
);
export default DepositionIcon;
