/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const DesktopIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="#181E53"
      fill-rule="evenodd"
      d="M14 2H2a1 1 0 00-1 1v7.6a1 1 0 001 1h4v1H3V14h10v-1.4h-3v-1h4a1 1 0 001-1V3a1 1 0 00-1-1zm-.4 7H2.4V3.4h11.2V9z"
      clip-rule="evenodd"
    />
  </svg>
);
export default DesktopIcon;
