/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const DiffIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M9.002 15v-2h6v2h-6zm-6-14h2v2.001h2v2h-2v1.99h-2v-1.99h-2l-.002-2h2.002V1zm1 9.6L5.592 9l1.4 1.411-1.59 1.59 1.6 1.6-1.4 1.4-1.6-1.6-1.6 1.6L1 13.6l1.602-1.6L1 10.406 2.414 9l1.588 1.6zm5-5.6V3h6v2h-6zm0 6V9h6v2h-6z"
    />
  </svg>
);
export default DiffIcon;
