/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const DownwardIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14 9.137l-1.254-1.225-3.85 3.763V1H7.104v10.675l-3.85-3.763L2 9.137 8 15z"
    />
  </svg>
);
export default DownwardIcon;
