/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const DownloadIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M7.12 8.525V1h1.75v7.525l3.5-3.5 1.224 1.225-4.987 4.987a.846.846 0 01-1.225 0L2.394 6.25 3.62 5.025l3.5 3.5zm6.124 4.725v-2.625h1.75v3.5c0 .525-.35.875-.875.875H1.87c-.525 0-.875-.35-.875-.875v-3.5h1.75v2.625h10.5z"
    />
  </svg>
);
export default DownloadIcon;
