/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const DownwardIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M9.137 2L7.912 3.254l3.763 3.85H1v1.792h10.675l-3.763 3.85L9.137 14 15 8z"
    />
  </svg>
);
export default DownwardIcon;
