/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const EditIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M11.238 1.262a.846.846 0 00-1.225 0l-8.75 8.75a.794.794 0 00-.263.613v3.5c0 .525.35.875.875.875h3.5a.794.794 0 00.613-.263l8.75-8.75a.846.846 0 000-1.225l-3.5-3.5zM5.025 13.25H2.75v-2.275L8 5.725 10.275 8l-5.25 5.25zM11.5 6.775L9.225 4.5l1.4-1.4L12.9 5.375l-1.4 1.4z"
    />
  </svg>
);
export default EditIcon;
