/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const EmailIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.125 2H1.875A.866.866 0 001 2.857v10.286c0 .474.392.857.875.857h12.25a.866.866 0 00.875-.857V2.857A.866.866 0 0014.125 2zm-.875 10.286H2.75v-5.38L7.566 9.6c.27.151.6.151.868 0l4.816-2.696v5.38zm0-7.355L8 7.871 2.75 4.93V3.714h10.5v1.217z"
    />
  </svg>
);
export default EmailIcon;
