/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ErrorIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 1C4.15 1 1 4.15 1 8s3.15 7 7 7 7-3.15 7-7-3.15-7-7-7z"
    />
    <path
      fill="#FFF"
      d="M11 9.8L9.8 11 8 9.2 6.2 11 5 9.8 6.8 8 5 6.2 6.2 5 8 6.8 9.8 5 11 6.2 9.2 8z"
    />
  </svg>
);
export default ErrorIcon;
