/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const EuroIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 14 14"
  >
    <path
      fill="currentColor"
      d="M13.125 0c.483 0 .875.392.875.875v12.25a.875.875 0 01-.875.875H.875A.875.875 0 010 13.125V.875C0 .392.392 0 .875 0h12.25zM8.108 10.16c-1.22 0-2.275-.69-2.8-1.702h2.566v-.972H4.987A3.262 3.262 0 014.948 7c0-.165.015-.326.04-.486h2.886v-.973H5.308a3.158 3.158 0 014.857-.938l.86-.86a4.355 4.355 0 00-2.917-1.118 4.378 4.378 0 00-4.122 2.916h-1.36v.973h1.136a4.105 4.105 0 000 .972H2.625v.972h1.361a4.377 4.377 0 004.122 2.917 4.345 4.345 0 002.917-1.118l-.865-.86a3.113 3.113 0 01-2.052.763z"
    />
  </svg>
);
export default EuroIcon;
