/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const FacebookIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M6.418 15L6.4 8.875H4V6.25h2.4V4.5C6.4 2.138 7.738 1 9.664 1c.922 0 1.715.075 1.946.108v2.469h-1.336c-1.048 0-1.25.545-1.25 1.344V6.25H12l-.8 2.625H9.024V15H6.418z"
    />
  </svg>
);
export default FacebookIcon;
