/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const FileIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M3.714 2.75h5.143v3.5h3.429v7H3.714V2.75zM14 14.125v-8.75L9.714 1H2.857C2.343 1 2 1.35 2 1.875v12.25c0 .525.343.875.857.875h10.286c.514 0 .857-.35.857-.875z"
    />
  </svg>
);
export default FileIcon;
