/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const FineIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.417 3a.57.57 0 01.583.556v2.777a.57.57 0 01-.583.556c-.644 0-1.167.498-1.167 1.111s.523 1.111 1.167 1.111a.57.57 0 01.583.556v2.777a.57.57 0 01-.583.556H1.583A.57.57 0 011 12.444V9.667a.57.57 0 01.583-.556c.644 0 1.167-.498 1.167-1.111s-.523-1.111-1.167-1.111A.57.57 0 011 6.333V3.556A.57.57 0 011.583 3h12.834zM9.313 5.917L8 7.167l-1.313-1.25-.875.833L7.125 8 5.812 9.25l.875.833L8 8.833l1.313 1.25.874-.833L8.876 8l1.313-1.25-.876-.833z"
    />
  </svg>
);
export default FineIcon;
