/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const FunicularIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="#78469A"
      fillRule="evenodd"
      d="M14.062 5.273A.35.35 0 0013.721 5H2.279a.35.35 0 00-.341.273L1.009 9.38a.451.451 0 00.074.35l.812 1.124a.35.35 0 00.283.145h11.643a.35.35 0 00.284-.145l.812-1.123a.451.451 0 00.074-.351l-.929-4.108zM3.75 8.183a.35.35 0 01-.35.35H2.35a.35.35 0 01-.342-.426l.31-1.4a.35.35 0 01.34-.275H3.4a.35.35 0 01.35.35v1.4zm3.5 0a.35.35 0 01-.35.35H4.799a.35.35 0 01-.35-.35V6.781a.35.35 0 01.35-.35h2.1a.35.35 0 01.35.35v1.4zm3.51 0a.35.35 0 01-.35.35h-2.1a.35.35 0 01-.35-.35V6.781a.35.35 0 01.35-.35h2.1a.35.35 0 01.35.35v1.4zm3.073.219a.35.35 0 01-.272.131H11.81a.35.35 0 01-.35-.35V6.782a.35.35 0 01.35-.35H13.251a.35.35 0 01.342.275l.309 1.4a.347.347 0 01-.07.295z"
      clipRule="evenodd"
    />
    <path
      fill="#78469A"
      fillRule="evenodd"
      d="M2 12h12v1H2z"
      clipRule="evenodd"
    />
  </svg>
);
export default FunicularIcon;
