/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const GoalIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M5.818 2.312L14 6.25l-8.182 3.937v3.938c0 .525-.363.875-.909.875S4 14.65 4 14.125V1.875C4 1.35 4.364 1 4.91 1s.908.35.908.875v.437z"
    />
  </svg>
);
export default GoalIcon;
