/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const GridViewIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8.875 15V8.875H15V15H8.875zm0-14H15v6.125H8.875V1zM1 8.875h6.125V15H1V8.875zM1 1h6.125v6.125H1V1z"
    />
  </svg>
);
export default GridViewIcon;
