/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const HeartIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M11.15 1C9.837 1 8.7 1.68 8 2.7 7.3 1.68 6.162 1 4.85 1 2.75 1 1 2.7 1 4.739 1 8.477 8 14 8 14s7-5.523 7-9.261C15 2.699 13.25 1 11.15 1"
    />
  </svg>
);
export default HeartIcon;
