/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const HelicopterIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="#800664"
      fillRule="evenodd"
      d="M15 4.671V4H4v.671h5.17v1.127h-.52a.65.65 0 00-.65.65v.554H2.558l-.315-.863a.21.21 0 00-.2-.139h-.832A.211.211 0 001 6.211l.009 1.907a.212.212 0 00.176.206L8 9.475v.875c0 .359.291.65.65.65h4.7a.65.65 0 00.65-.65V9.198c0-1.875-1.526-3.4-3.4-3.4h-.76V4.67H15zm-4.638 2.242v-.097a.229.229 0 01.221-.19h.526c.891 0 1.631.66 1.76 1.516.014.083.01.128-.012.17-.03.051-.084.085-.21.085-.195 0-.888-.002-2.064 0a.22.22 0 01-.221-.22V6.913z"
      clipRule="evenodd"
    />
    <path
      fill="#800664"
      fillRule="evenodd"
      d="M9 11.999h4v1H9z"
      clipRule="evenodd"
    />
  </svg>
);
export default HelicopterIcon;
