/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const HomeIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M10.58 15h1.749c.524 0 .874-.352.874-.88V7.968h.875c.262 0 .524-.088.7-.264.35-.351.262-.879-.088-1.23L8.568 1.198a.916.916 0 00-1.136 0L1.31 6.473c-.35.351-.437.879-.087 1.23.087.176.35.264.612.264h.874v6.154c0 .527.35.879.875.879h1.749c.524 0 .874-.352.874-.88v-2.636h3.498v2.637c0 .527.35.879.875.879"
    />
  </svg>
);
export default HomeIcon;
