/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const HorizontalIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M2.75 9.5a1.75 1.75 0 110-3.5 1.75 1.75 0 010 3.5zM8 9.5A1.75 1.75 0 118 6a1.75 1.75 0 010 3.5zm5.25 0a1.75 1.75 0 110-3.5 1.75 1.75 0 010 3.5z"
    />
  </svg>
);
export default HorizontalIcon;
