/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const ImageIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="#181E53"
      fill-rule="evenodd"
      d="M14 1H2a1 1 0 00-1 1v12a1 1 0 001 1h12a1 1 0 001-1V2a1 1 0 00-1-1zM6 4a1 1 0 110 2 1 1 0 010-2zm-3 8l2-4 2 2 3-4 3 6H3z"
      clip-rule="evenodd"
    />
  </svg>
);
export default ImageIcon;
