/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const InstagramIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M4.5 2.75c-.818 0-1.75.932-1.75 1.75v7c0 .834.916 1.75 1.75 1.75h7c.818 0 1.75-.932 1.75-1.75v-7c0-.818-.932-1.75-1.75-1.75h-7zm7 12.25h-7C2.701 15 1 13.299 1 11.5v-7C1 2.701 2.701 1 4.5 1h7C13.299 1 15 2.701 15 4.5v7c0 1.799-1.701 3.5-3.5 3.5zM8 6.25c-.965 0-1.75.785-1.75 1.75S7.035 9.75 8 9.75 9.75 8.965 9.75 8 8.965 6.25 8 6.25m0 5.25c-1.93 0-3.5-1.57-3.5-3.5S6.07 4.5 8 4.5s3.5 1.57 3.5 3.5-1.57 3.5-3.5 3.5zm3.627-7.935a.84.84 0 110 1.68.84.84 0 010-1.68z"
    />
  </svg>
);
export default InstagramIcon;
