/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const InternationalIcon: IconComponentType = ({
  className,
  ...rest
}) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 14 14"
  >
    <path
      fill="currentColor"
      d="M7 14c-3.85 0-7-3.15-7-7s3.15-7 7-7 7 3.15 7 7-3.15 7-7 7zM7 1.75C4.112 1.75 1.75 4.112 1.75 7S4.112 12.25 7 12.25 12.25 9.887 12.25 7 9.887 1.75 7 1.75zM3.675 7c.263-.7 1.4-.875 1.925-.613.525.263.963 0 1.488.613.437.612.874.437.962 1.312.087.875-1.138 2.45-1.4 2.888-.35.437-1.225-.088-1.225-1.313s-.613-1.312-.963-1.4C4.025 8.312 3.15 8.225 3.675 7m2.187-3.938s-.175.438.175.525c.875.175.963.438 1.313.875.35.438-.088.875-.175 1.4-.088.438.262.7 1.05.525 1.05-.262 1.137.875 1.75.788.525-.088.962.787 1.225.875.087-.35.175-.7.175-1.05 0-1.663-.963-3.063-2.275-3.85-.35-.088-.7-.088-1.05-.088-.7 0-1.313-.437-2.188 0"
    />
  </svg>
);
export default InternationalIcon;
