/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const InterrailIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M10.917 10.273c.659 0 1.26-.231 1.75-.606v4.742c0 .326-.262.59-.584.59H3.917a.587.587 0 01-.584-.59V9.667c.49.375 1.091.606 1.75.606h1.75v.59c0 .327.262.591.584.591h1.166a.587.587 0 00.584-.59v-.591h1.75zM5.083 9.09c-.966 0-1.75-.794-1.75-1.773V4.955C3.333 3.323 4.64 2 6.25 2h3.5c1.61 0 2.917 1.323 2.917 2.955v2.363c0 .98-.784 1.773-1.75 1.773h-1.75V8.5a.587.587 0 00-.584-.591H7.417a.587.587 0 00-.584.591v.59h-1.75zM13.833 15V6.836A1.769 1.769 0 0115 8.5v5.909c0 .326-.261.59-.583.59h-.584zM2.167 6.836V15h-.584A.587.587 0 011 14.41V8.5c0-.77.489-1.419 1.167-1.664z"
    />
  </svg>
);
export default InterrailIcon;
