/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const ItalicIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M12 2.75V1H6.75v1.75h1.112c.266 0 .47.236.433.5l-1.322 9.248a.874.874 0 01-.865.752H5V15h5.25v-1.75H9.138a.438.438 0 01-.433-.5l1.321-9.248a.876.876 0 01.866-.752H12z"
    />
  </svg>
);
export default ItalicIcon;
