/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const LeftArrowIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M5.105 6.833L3.69 8.247l5.658 5.656 1.413-1.414-4.242-4.242 4.242-4.243L9.348 2.59z"
    />
  </svg>
);
export default LeftArrowIcon;
