/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const LikeIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M1 8h1.747v7H1V8zm11.62-1.75c.698 0 1.397.262 1.834.875.437.437.612 1.137.524 1.837l-.699 4.025C14.105 14.125 13.144 15 12.008 15H4.495V8C4.582 8 6.59 1.437 6.59 1.437c0-.262.262-.437.524-.437 1.049 0 1.748.437 1.748 1.75v3.5h3.756z"
    />
  </svg>
);
export default LikeIcon;
