/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const LinkIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M11.876 9.91l-1.19-1.19 1.97-1.975a2.397 2.397 0 00-.004-3.307 2.367 2.367 0 00-1.675-.742 2.374 2.374 0 00-1.705.661L7.307 5.342 6.11 4.146 8.08 2.16a4.06 4.06 0 015.725.043 4.099 4.099 0 01.05 5.737l-1.978 1.97zM4.125 6.122l1.19 1.19-1.97 1.976a2.396 2.396 0 003.383 3.388l1.966-1.986 1.195 1.197-1.968 1.987a4.06 4.06 0 01-5.678.002l-.047-.045a4.1 4.1 0 01-.05-5.738l1.979-1.97zm2.612 4.432L5.569 9.385l4.315-4.314 1.168 1.168-4.315 4.314z"
    />
  </svg>
);
export default LinkIcon;
