/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ListViewIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M1 3h10.5v2H1V3zm12.25 0H15v2h-1.75V3zM1 7h10.5v2H1V7zm12.25 0H15v2h-1.75V7zM1 11h10.5v2H1v-2zm12.25 0H15v2h-1.75v-2z"
    />
  </svg>
);
export default ListViewIcon;
