/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const LoadingIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 15A7 7 0 118 1a7 7 0 010 14zm0-2A5 5 0 108 3a5 5 0 000 10z"
    />
    <path
      fill="currentColor"
      d="M1.338 10.138l1.893-.656c.328 1.314 1.305 2.482 2.766 3.095 1.095.46 2.28.532 3.365.279l.718 1.88a7.466 7.466 0 01-4.928-.346c-1.966-.852-3.306-2.444-3.814-4.252z"
    />
  </svg>
);
export default LoadingIcon;
