/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const LocationIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.428 1.023L1.297 5.4a.435.435 0 000 .824l6.257 2.085a.222.222 0 01.137.137l2.086 6.257a.434.434 0 00.823 0l4.377-13.131a.434.434 0 00-.55-.55"
    />
  </svg>
);
export default LocationIcon;
