/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const LuggageIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M13 6.25V4.5c0-.525-.333-.875-.833-.875H10.5v-1.75c0-.525-.333-.875-.833-.875H6.333c-.5 0-.833.35-.833.875v1.75H3.833c-.5 0-.833.35-.833.875v1.75h10zm-5.833-3.5h1.666v.875H7.167V2.75zM3 8h10v4.375c0 .525-.333.875-.833.875h-.834V15h-2.5v-1.75H7.167V15h-2.5v-1.75h-.834c-.5 0-.833-.35-.833-.875V8z"
    />
  </svg>
);
export default LuggageIcon;
