/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const MapIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M13.775 1.078L9.75 2.655 6.6 1.078c-.175-.088-.438-.088-.7 0L1.525 2.83c-.35.088-.525.438-.525.789v10.515a.862.862 0 001.225.788l4.025-1.577 3.15 1.577a.965.965 0 00.7 0l4.375-1.665c.35-.087.525-.438.525-.788V1.866a.862.862 0 00-1.225-.788zm-6.65 2.19l1.75.877v8.587l-1.75-.877V3.268zm-4.375.964l2.625-1.051v8.587L2.75 12.819V4.232zm10.5 7.623l-2.625.964V4.232l2.625-1.051v8.674z"
    />
  </svg>
);
export default MapIcon;
