/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const MapPinIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M2.5 6.741c0 3.54 4.77 7.896 4.77 7.896a1.042 1.042 0 001.46 0s4.77-4.356 4.77-7.896C13.5 3.105 10.658 1 8 1S2.5 3.105 2.5 6.741zM8 8.655c-1.008 0-1.833-.861-1.833-1.914S6.992 4.827 8 4.827s1.833.862 1.833 1.914S9.008 8.655 8 8.655z"
    />
  </svg>
);
export default MapPinIcon;
