/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const MenuIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M1 3h14v1.766H1V3zm0 4.117h14v1.766H1V7.117zm0 4.117h14V13H1v-1.766z"
    />
  </svg>
);
export default MenuIcon;
