/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const MergeProfilesIcon: IconComponentType = ({
  className,
  ...rest
}) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 9.75c-.965 0-1.75-.785-1.75-1.75S7.035 6.25 8 6.25 9.75 7.035 9.75 8 8.965 9.75 8 9.75zM2.494 1.256l1.75 1.75L6.25 1v5.25H1l2.006-2.006-1.75-1.75 1.238-1.238zm10.5 2.988L15 6.25H9.75V1l2.006 2.006 1.75-1.75 1.238 1.238-1.75 1.75zM9.75 9.75H15l-2.006 2.006 1.75 1.75-1.238 1.238-1.75-1.75L9.75 15V9.75zm-6.744 2.006L1 9.75h5.25V15l-2.006-2.006-1.75 1.75-1.238-1.238 1.75-1.75z"
    />
  </svg>
);
export default MergeProfilesIcon;
