/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const NegativeIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path fill="#FF5959" d="M0 14.799h15.783v-1.422H0z" />
    <path
      fill="#FFF"
      d="M0 2h6.45v1.567H1.674v2.312h4.236v1.566H1.675v2.237H6.45v1.566H0V2zm14.107 0h1.676v9.248h-.18L9.848 5.752v5.496H8.173V2h.179l5.755 5.597V2z"
    />
  </svg>
);
export default NegativeIcon;
