/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const NorwayIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path fill="#D80027" d="M1 14h14V4H1z" />
    <path fill="#D80027" d="M1 14h14V4H1z" />
    <path
      fill="#FFF"
      d="M5.16 4v3.696H1v2.608h4.16V14h2.434v-3.696H15V7.696H7.594V4z"
    />
    <path
      fill="#0052B4"
      d="M5.768 4v4.348H1v1.304h4.768V14h1.218V9.652H15V8.348H6.986V4z"
    />
  </svg>
);
export default NorwayIcon;
