/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const OrganizationIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M12.375 13.25c-.525 0-.875-.35-.875-.875s.35-.875.875-.875.875.35.875.875-.35.875-.875.875M8 4.5c-.525 0-.875-.35-.875-.875s.35-.875.875-.875.875.35.875.875S8.525 4.5 8 4.5m-4.375 8.75c-.525 0-.875-.35-.875-.875s.35-.875.875-.875.875.35.875.875-.35.875-.875.875m8.75-3.5c-.525 0-.963.175-1.4.437l-2.1-1.75V6.075a2.549 2.549 0 001.75-2.45C10.625 2.137 9.488 1 8 1S5.375 2.137 5.375 3.625c0 1.137.7 2.1 1.75 2.45v2.362l-2.1 1.663c-.438-.175-.875-.35-1.4-.35C2.138 9.75 1 10.887 1 12.375S2.138 15 3.625 15s2.625-1.138 2.625-2.625c0-.263-.087-.613-.175-.875L8 10.012 9.925 11.5c-.087.262-.175.525-.175.875 0 1.487 1.137 2.625 2.625 2.625S15 13.862 15 12.375 13.863 9.75 12.375 9.75"
    />
  </svg>
);
export default OrganizationIcon;
