/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const ParkIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8.527 4c1.69 0 2.788.79 2.788 2.348 0 1.6-1.007 2.52-2.799 2.52H7.201V12H5.6V4h2.927zm.044 3.414c.885.005 1.209-.487 1.208-1.025-.001-.626-.399-.995-1.22-.995H7.201v2.02h1.37zM8 15A7 7 0 118 1a7 7 0 010 14zm0-1A6 6 0 108 2a6 6 0 000 12z"
    />
  </svg>
);
export default ParkIcon;
