/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ParkinghouseIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 12 14"
  >
    <path
      fill="currentColor"
      d="M6.493 4.5H3.2v9h1.801V9.975h1.48c2.015 0 3.148-1.035 3.148-2.833C9.63 5.387 8.394 4.5 6.493 4.5m.05 3.84H5V6.069H6.53c.923 0 1.371.415 1.372 1.12.002.605-.363 1.158-1.359 1.153M12 4.1L6 1.7 0 4.1V2.807L5.555.585c.285-.114.605-.114.89 0L12 2.808V4.1z"
    />
  </svg>
);
export default ParkinghouseIcon;
