/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const PeriodeTicketIcon: IconComponentType = ({
  className,
  ...rest
}) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M2.75 4.5h10.5V2.75H2.75V4.5zM14.125 1c.484 0 .875.392.875.875V8h-1.75V6.25H2.75v3.5h2.625v1.75h-3.5A.875.875 0 011 10.625v-8.75C1 1.392 1.391 1 1.875 1h12.25zm0 9.625v1.75H11.5V15H9.75v-2.625H7.125v-1.75H9.75V8h1.75v2.625h2.625z"
    />
  </svg>
);
export default PeriodeTicketIcon;
