/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const PhoneIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="#181E53"
      fill-rule="evenodd"
      d="M14.738 11.687l-2.317-2.331a.898.898 0 00-1.273-.002L9.09 11.413 4.595 6.919l2.062-2.062a.9.9 0 00.001-1.27L4.339 1.263a.899.899 0 00-1.272 0L1.004 3.326 1 3.324c0 6.453 5.231 11.684 11.685 11.684l2.052-2.052a.898.898 0 00.001-1.269"
      clip-rule="evenodd"
    />
  </svg>
);
export default PhoneIcon;
