/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const PlaneIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="#800664"
      fillRule="evenodd"
      d="M14.833 5.682a.216.216 0 00-.044-.03l-.016-.011-.043-.025c-.146-.084-1.008-.42-1.478-.576a.761.761 0 00-.398-.024L9.037 6.044 5.21 4.438c-.273-.118-.318-.14-.57-.125l-.794.076c-.171.018-.198.158-.055.294L6.01 6.858 3.621 7.5l-2.13-.824c-.176-.069-.231-.068-.323-.043l-.08.022c-.063.016-.09.056-.088.1.002.057.046.076.19.228 0 0 2.873 2.805 3.033 2.948a.221.221 0 00.204.048l10.138-2.731a.219.219 0 00.151-.144c.131-.4.313-1.058.28-1.179a.458.458 0 00-.163-.243zm-1.252.206l-.271.073c-.03.008-.074.026-.122.006l-.46-.169a.139.139 0 01-.087-.138.141.141 0 01.103-.127l.271-.073a.142.142 0 01.088.005l.506.204c.056.023.086.055.082.115s-.052.09-.11.104z"
      clipRule="evenodd"
    />
    <path
      fill="#800664"
      fillRule="evenodd"
      d="M2 11.999h12v1H2z"
      clipRule="evenodd"
    />
  </svg>
);
export default PlaneIcon;
