/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const PositionIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="#181E53"
      fill-rule="evenodd"
      d="M14.428 1.023L1.297 5.4a.434.434 0 000 .824l6.257 2.085a.217.217 0 01.137.137l2.085 6.257a.434.434 0 00.824 0l4.377-13.131a.434.434 0 00-.549-.549z"
      clip-rule="evenodd"
    />
  </svg>
);
export default PositionIcon;
