/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const PricelistIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M6.25 4.5h7V2.75h-7V4.5zm0 3.5h7V6.25h-7V8zM4.5 1H15v12.25a1.75 1.75 0 11-3.5 0v-3.5h-7V1zm5.25 12.25c0 .64.185 1.233.486 1.75H3.625A2.625 2.625 0 011 12.375V11.5h8.75v1.75z"
    />
  </svg>
);
export default PricelistIcon;
