/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const PrinterIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="#181E53"
      fill-rule="evenodd"
      d="M14.2 5.6H1.8a.8.8 0 00-.8.8v5.2a.8.8 0 00.8.8H4v1.8a.8.8 0 00.8.8h6.4a.8.8 0 00.8-.8v-1.8h2.2a.8.8 0 00.8-.8V6.4a.8.8 0 00-.8-.8zm-3.6 8H5.4V8.4h5.2v5.2zM11.2 1H4.8a.8.8 0 00-.8.8v2.4h8V1.8a.8.8 0 00-.8-.8z"
      clip-rule="evenodd"
    />
  </svg>
);
export default PrinterIcon;
