/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const QuestionIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 1C4.15 1 1 4.15 1 8s3.15 7 7 7 7-3.15 7-7-3.15-7-7-7"
    />
    <path
      fill="#FFF"
      d="M9.313 8.35c-.438.262-.438.35-.438.525v.875h-1.75v-.875c0-1.138.7-1.663 1.225-2.013.438-.262.525-.35.525-.612 0-.525-.35-.875-.875-.875-.35 0-.613.175-.787.437l-.438.788-1.488-.875.438-.788C6.163 4.15 7.038 3.625 8 3.625c1.488 0 2.625 1.137 2.625 2.625 0 1.225-.787 1.75-1.313 2.1zM8 12.375c-.525 0-.875-.35-.875-.875s.35-.875.875-.875.875.35.875.875-.35.875-.875.875z"
    />
  </svg>
);
export default QuestionIcon;
