/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const ReferenceIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M4.733 5.667a.933.933 0 110-1.867.933.933 0 010 1.867m10.13 2.936L7.397 1.137A.465.465 0 007.067 1H3.333a.465.465 0 00-.33.137L1.137 3.003a.465.465 0 00-.137.33v3.734c0 .123.049.242.137.33l7.466 7.466a.465.465 0 00.66 0l5.6-5.6a.466.466 0 000-.66"
    />
  </svg>
);
export default ReferenceIcon;
