/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const RefreshIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8.436 1l.674 6.054 2.021-1.986c1.829 1.797 1.829 4.824 0 6.621-.866.946-2.118 1.42-3.369 1.42s-2.503-.474-3.369-1.42c-1.829-1.797-1.829-4.824 0-6.621.578-.568 1.348-1.041 2.214-1.23L6.029 2.04a6.607 6.607 0 00-3.08 1.702C.35 6.297.35 10.46 2.95 13.108 4.201 14.338 5.933 15 7.666 15c1.829 0 3.465-.662 4.716-1.892 2.6-2.554 2.6-6.716 0-9.365l2.118-2.08L8.436 1z"
    />
  </svg>
);
export default RefreshIcon;
