/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ReportsIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M9.714 4.5c.515 0 .857.35.857.875v8.75c0 .525-.342.875-.857.875H2.857C2.343 15 2 14.65 2 14.125v-8.75c0-.525.343-.875.857-.875h6.857zM13.143 1c.514 0 .857.35.857.875v10.5h-1.714V2.75H4.57V1h8.572z"
    />
  </svg>
);
export default ReportsIcon;
