/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ResetIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M4.5 9.308c1.381 0 2.5 1.162 2.5 2.596S5.881 14.5 4.5 14.5 2 13.338 2 11.904s1.119-2.596 2.5-2.596zm3.878-8.212c3.65 0 6.622 3.006 6.622 6.702S12.029 14.5 8.378 14.5v-1.915c2.608 0 4.73-2.147 4.73-4.787S10.986 3.01 8.378 3.01a4.723 4.723 0 00-3.344 1.402l2.02 2.044L1 7.127 1.662 1l2.036 2.06a6.602 6.602 0 014.68-1.964z"
    />
  </svg>
);
export default ResetIcon;
