/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const RightArrowIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M5.25 4.005l4.243 4.243L5.25 12.49l1.415 1.414 5.656-5.656-1.415-1.414L6.665 2.59z"
    />
  </svg>
);
export default RightArrowIcon;
