/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const RunningIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <g fill="currentColor" fillRule="evenodd" clipRule="evenodd">
      <path d="M10.132 4a1.25 1.25 0 100-2.5 1.25 1.25 0 000 2.5z" />
      <path d="M13.533 6.586l-1.734.117a.15.15 0 01-.12-.048L10.316 5.18a1.242 1.242 0 00-.347-.263l-1.6-.82a1 1 0 00-.828-.015l-2.213.95a.6.6 0 00-.237.183l-1.59 2.048a.428.428 0 00.591.618L5.67 6.137a.25.25 0 01.098-.066l1.408-.525-1.01 2.412a1.4 1.4 0 00-.062 1.049l.038.11a1.4 1.4 0 00.648.777l2.667 1.478.08.082 1.69 3.205a.6.6 0 101.083-.518l-1.423-3.428a1 1 0 00-.327-.42L8.5 8.764l1.142-2.44 1.518 1.354a.5.5 0 00.42.119l2.03-.36a.428.428 0 00-.078-.851z" />
      <path d="M5.708 9.6a1.32 1.32 0 01-.075-.282l-.975 1.75-2.886 1.134a.6.6 0 10.394 1.134l3.371-.959 1.133-1.851-.33-.183c-.353-.228-.513-.456-.632-.743z" />
    </g>
  </svg>
);
export default RunningIcon;
