/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const SalesplaceIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8.857 4.937h.857V8h-.857a.433.433 0 00-.428.437v5.688H7.57V9.75a.433.433 0 00-.428-.438h-.857V4.937h.857A.433.433 0 007.57 4.5v-.875h.858V4.5c0 .242.191.437.428.437zM11 10.625H9.714V9.75H11v.875zm.429 1.75h1.285v.875H11.43v-.875zm0-1.313h1.285v.875H11.43v-.875zm0-1.312h1.285v.875H11.43V9.75zM11 11.937H9.714v-.875H11v.875zm0 1.313H9.714v-.875H11v.875zm-4.714-1.313H5v-.875h1.286v.875zm0 1.313H5v-.875h1.286v.875zM4.57 11.937H3.286v-.875H4.57v.875zm0 1.313H3.286v-.875H4.57v.875zM8 1a.433.433 0 00-.429.437V2.75h-.428a.433.433 0 00-.429.437v.875h-.857a.433.433 0 00-.428.438v4.812h-3A.433.433 0 002 9.75v4.812c0 .242.192.438.429.438H13.57a.433.433 0 00.429-.438V8.437A.433.433 0 0013.571 8h-3V4.5a.433.433 0 00-.428-.438h-.857v-.875a.433.433 0 00-.429-.437H8.43V1.437A.433.433 0 008 1z"
    />
  </svg>
);
export default SalesplaceIcon;
