/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const SanntidIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M3 11a2 2 0 11.001 3.999A2 2 0 013 11zm12 4h-2.7C12.3 8.8 7.2 3.7 1 3.7V1c7.7 0 14 6.3 14 14zm-4.7 0H7.7c0-3.7-3-6.7-6.7-6.7V5.7c5.1 0 9.3 4.2 9.3 9.3z"
    />
  </svg>
);
export default SanntidIcon;
