/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ScooterIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12.5 11c-.019 0-.036.005-.055.005l-2.224-7.68A.45.45 0 009.79 3H7.5v.8h1.95a.1.1 0 01.097.072l1.53 5.281a.1.1 0 01-.02.093l-2.398 2.819a.1.1 0 01-.076.035H4.94A1.496 1.496 0 002 12.5a1.496 1.496 0 002.94.4H8.79a.45.45 0 00.343-.159l2.224-2.615.324 1.12c-.41.267-.682.728-.682 1.254a1.5 1.5 0 101.5-1.5zm-9 2.2a.7.7 0 11.002-1.402A.7.7 0 013.5 13.2zm9 0a.7.7 0 11.002-1.402.7.7 0 01-.002 1.402z"
      clipRule="evenodd"
    />
  </svg>
);
export default ScooterIcon;
