/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const SearchIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M7.212 11.521c-2.45 0-4.462-1.913-4.462-4.348 0-2.434 2.012-4.434 4.462-4.434s4.462 2 4.462 4.434c0 2.435-2.012 4.348-4.462 4.348zm7.784 2.26l-2.884-2.955a5.935 5.935 0 001.225-3.653C13.337 3.783 10.625 1 7.212 1S1 3.782 1 7.173c0 3.392 2.8 6.174 6.212 6.174 1.4 0 2.712-.434 3.675-1.217L13.772 15l1.224-1.22z"
    />
  </svg>
);
export default SearchIcon;
