/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const SeatIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M3.334 3.56a1.425 1.425 0 01-.342-1.963 1.392 1.392 0 011.943-.344c.627.45.78 1.322.342 1.962a1.394 1.394 0 01-1.943.344zm7.417 9.394v1.407H5.834a3.498 3.498 0 01-3.447-2.982L1 4.516h1.393l1.372 6.652a2.09 2.09 0 002.062 1.786h4.924zm-3.239-2.813h3.975l2.395 3.667a.727.727 0 01-.186.99l-.113.079a.682.682 0 01-.97-.2l-1.54-2.426h-4.62A2.1 2.1 0 014.4 10.535l-.94-4.163c-.202-.95.424-1.68 1.282-1.835h.014c.23-.042.595-.009.81.079.282.115.695.309.872 1.127l1.075 4.398z"
    />
  </svg>
);
export default SeatIcon;
