/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const SettingsIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 10.625c-1.488 0-2.625-1.138-2.625-2.625S6.512 5.375 8 5.375 10.625 6.512 10.625 8 9.488 10.625 8 10.625m4.637-5.075l.963-1.838-1.225-1.225-1.837.963c-.263-.175-.613-.263-.963-.35l-.7-2.1h-1.75l-.7 2.012c-.263.088-.613.175-.875.35L3.713 2.4 2.4 3.712l.963 1.838c-.176.262-.263.612-.35.875L1 7.125v1.75l2.013.7c.087.35.262.612.35.962L2.4 12.375 3.625 13.6l1.837-.963c.263.175.613.263.963.35l.7 2.013h1.75l.7-2.013c.35-.087.613-.262.963-.35l1.837.963 1.225-1.225-.963-1.838c.175-.262.263-.612.35-.962l2.013-.7v-1.75l-2.013-.7c-.087-.263-.175-.613-.35-.875"
    />
  </svg>
);
export default SettingsIcon;
