/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const ShareIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.125 15H1.875C1.35 15 1 14.657 1 14.143V3.857C1 3.343 1.35 3 1.875 3H4.5v1.714H2.75v8.572h10.5V9H15v5.143c0 .514-.35.857-.875.857zM10 3.4V1l5 4-5 4V6.6C7 6.6 5.917 7.64 5 9c0-3.6 2.333-5.6 5-5.6z"
    />
  </svg>
);
export default ShareIcon;
