/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const ShoppingCartIcon: React.FC<IconProps> = ({
  className,
  ...rest
}) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.158 3.625c.702 0 .965.7.79 1.137l-1.755 5.25a.842.842 0 01-.79.613H5.387c-.439 0-.79-.263-.877-.7L2.929 2.75H1V1h2.632c.438 0 .789.262.877.7l.438 1.925h9.21zM5.386 11.5c.97 0 1.754.783 1.754 1.75S6.355 15 5.386 15s-1.754-.783-1.754-1.75.785-1.75 1.754-1.75zm7.018 0c.969 0 1.754.783 1.754 1.75S13.373 15 12.404 15s-1.755-.783-1.755-1.75.785-1.75 1.755-1.75z"
    />
  </svg>
);
export default ShoppingCartIcon;
