/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const SkypeIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 12.025c-2.362 0-3.413-1.138-3.413-2.013 0-.437.35-.787.788-.787.963 0 .787 1.4 2.625 1.4.963 0 1.488-.525 1.488-1.05 0-1.05-1.225-.875-2.888-1.313-1.662-.437-1.925-1.312-1.925-2.187 0-1.75 1.663-2.45 3.238-2.45 1.487 0 3.15.787 3.15 1.837 0 .438-.438.7-.876.7-.874 0-.7-1.225-2.45-1.225-.875 0-1.312.35-1.312.963 0 .787 1.575.962 2.8 1.225 1.663.437 2.1 1.4 2.1 2.275.088 1.575-1.05 2.625-3.325 2.625m6.475-2.888c.087-.35.525-3.325-1.837-5.862-2.188-2.363-5.6-1.925-5.95-1.838C6.161 1.175 5.55 1 4.937 1 1.874 1 1 3.887 1 4.937s.525 1.925.525 1.925c-.35 1.4.087 2.888.35 3.675.787 2.013 2.712 3.15 3.5 3.5 1.925.788 3.5.438 3.763.438.612.35 1.224.525 1.924.525 1.05 0 3.938-.875 3.938-3.938 0-1.05-.525-1.925-.525-1.925"
    />
  </svg>
);
export default SkypeIcon;
