/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const StandardedIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M7.4 1.225c.3-.3.9-.3 1.2 0l5 4-1.2 1.6-4.4-3.5-4.4 3.5-1.2-1.6 5-4zm.6 11.5l4.4-3.5 1.2 1.6-5 4c-.2.1-.4.2-.6.2s-.4-.1-.6-.2l-5-4 1.2-1.6 4.4 3.5z"
    />
  </svg>
);
export default StandardedIcon;
