/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const StandingIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <g fill="currentColor" fillRule="evenodd" clipRule="evenodd">
      <path d="M8 3.5a1.25 1.25 0 11-.001-2.499A1.25 1.25 0 018 3.5z" />
      <path d="M10.99 8.786l-.825-3.989A1 1 0 009.185 4h-2.37a1 1 0 00-.98.797l-.825 3.99a.428.428 0 00.836.184l.587-2.197h.047L6.5 10v4.4a.6.6 0 101.2 0l.101-4.338c.004-.033.026-.062.056-.062h.29c.032 0 .055.03.057.064L8.3 14.4a.6.6 0 101.2 0V10l.02-3.226h.047l.587 2.197a.428.428 0 00.836-.185z" />
    </g>
  </svg>
);
export default StandingIcon;
