/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const StarredIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M11.377 14.892L8 13.032l-3.377 1.86c-.636.355-1.393-.215-1.27-.966l.645-3.941-2.733-2.79c-.52-.532-.23-1.455.485-1.565l3.776-.574 1.69-3.586c.294-.627 1.275-.627 1.569 0l1.689 3.585 3.776.575c.716.109 1.005 1.032.486 1.563l-2.734 2.792.645 3.94c.124.755-.635 1.317-1.27.967"
    />
  </svg>
);
export default StarredIcon;
