/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const StatsIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M1.933 15C1.418 15 1 14.584 1 14.071s.418-.928.933-.928h12.134c.515 0 .933.416.933.928s-.418.929-.933.929H1.933zM6.6 11.286V2h2.8v9.286H6.6zm-4.667 0V5.714h2.8v5.572h-2.8zm9.334 0V7.57h2.8v3.715h-2.8z"
    />
  </svg>
);
export default StatsIcon;
