/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const StrollingIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <g fill="currentColor" fillRule="evenodd" clipRule="evenodd">
      <path d="M11.917 8.51l-1.361-1.68a.2.2 0 01-.029-.048l-.932-2.176A1 1 0 008.675 4H7.107a1 1 0 00-.837.453L5.143 6.177a.974.974 0 00-.15.392c-.088.575-.323 2.136-.323 2.136a.428.428 0 00.825.225l.554-2.132.518-.74.01 1.926c.002.303.091.6.257.853l1.708 2.621a.2.2 0 01.025.057l.824 3.02a.6.6 0 101.17-.27l-.53-3.019a1 1 0 00-.055-.192l-.978-2.498a.2.2 0 01-.014-.078l.062-2.193.507.894a.968.968 0 00.134.185l1.54 1.652a.428.428 0 00.69-.506z" />
      <path d="M6.507 9.362l-.073 1.815a.2.2 0 01-.012.06l-1.059 2.946a.6.6 0 101.113.45l1.298-2.776a.998.998 0 00.066-.188l.072-.252-1.405-2.055z" />
      <path d="M8.003 3.5a1.25 1.25 0 11-.001-2.499 1.25 1.25 0 010 2.499z" />
    </g>
  </svg>
);
export default StrollingIcon;
