/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const SuitcaseIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.125 12.375H9.75c0 .525-.35.875-.875.875h-1.75c-.525 0-.875-.35-.875-.875H1.875v1.75c0 .525.35.875.875.875h10.5c.525 0 .875-.35.875-.875v-1.75m0-7.875H11.5V1.875c0-.525-.35-.875-.875-.875h-5.25c-.525 0-.875.35-.875.875V4.5H1.875C1.35 4.5 1 4.85 1 5.375v5.25c0 .525.35.875.875.875H6.25v-.875c0-.525.35-.875.875-.875h1.75c.525 0 .875.35.875.875v.875h4.375c.525 0 .875-.35.875-.875v-5.25c0-.525-.35-.875-.875-.875zM6.25 2.75h3.5V4.5h-3.5V2.75z"
    />
  </svg>
);
export default SuitcaseIcon;
