/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const SwedenIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path fill="#0052B4" d="M1 14h14V4H1z" />
    <path
      fill="#FFDA44"
      d="M4.652 4v4.022H1v1.956h3.652V14h1.826V9.978H15V8.022H6.478V4z"
    />
  </svg>
);
export default SwedenIcon;
