/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const SwitchIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M10.913 1l3.43 3.496-3.431 3.497-1.217-1.208 1.39-1.415H2V3.62h9.086L9.684 2.195 10.913 1zM2 11.495l3.43-3.496 1.229 1.196-1.402 1.425h9.086v1.75H5.257l1.391 1.414-1.217 1.208L2 11.495z"
    />
  </svg>
);
export default SwitchIcon;
