/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const TaxiIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M13.998 7.233h-.002l-1.092-3.337c-.168-.512-.685-.863-1.272-.863H9.5v-.502a.498.498 0 00-.498-.498H6.997a.498.498 0 00-.497.498v.502H4.364c-.587 0-1.104.35-1.272.862L1.996 7.233h-.002a.998.998 0 00-.998.999v3.503c0 .275.223.498.499.498h.501v.667a1.1 1.1 0 002.2 0v-.667h7.6v.667a1.1 1.1 0 002.2 0v-.667h.501a.499.499 0 00.5-.498V8.232a.998.998 0 00-1-.999zM3.266 7.167l.84-2.74a.51.51 0 01.495-.344h6.79c.23 0 .431.141.494.345l.84 2.739c.011.033-.016.066-.054.066H3.32c-.037 0-.065-.033-.055-.066zm-.47 1.066c.44.002.8.36.8.804a.8.8 0 11-.8-.804zm10.4 1.6a.8.8 0 110-1.6.8.8 0 010 1.6z"
      clipRule="evenodd"
    />
  </svg>
);
export default TaxiIcon;
