/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const TeddyIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M15 3.187C15 1.962 14.037 1 12.812 1s-2.187.962-2.187 2.187v.175C9.838 3.012 8.962 2.75 8 2.75s-1.837.262-2.625.612v-.175C5.375 1.962 4.412 1 3.187 1S1 1.962 1 3.187c0 1.138.875 2.1 2.013 2.188a5.976 5.976 0 00-1.138 3.5C1.875 12.287 4.588 15 8 15s6.125-2.713 6.125-6.125a5.976 5.976 0 00-1.137-3.5A2.193 2.193 0 0015 3.187zM5.375 8c0-.525.35-.875.875-.875s.875.35.875.875-.35.875-.875.875-.875-.35-.875-.875zm4.375 4.375h-3.5V11.5h.875V9.75h1.75v1.75h.875v.875zm0-3.5c-.525 0-.875-.35-.875-.875s.35-.875.875-.875.875.35.875.875-.35.875-.875.875z"
    />
  </svg>
);
export default TeddyIcon;
