/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const TicketIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.416 2.587c.323 0 .583.248.583.556V5.92c0 .308-.26.556-.583.556-.643 0-1.167.498-1.167 1.11s.524 1.112 1.167 1.112c.323 0 .583.248.583.556v2.777c0 .308-.26.556-.583.556H1.584A.57.57 0 011 12.03V9.254a.57.57 0 01.584-.556c.643 0 1.166-.498 1.166-1.111s-.523-1.111-1.166-1.111A.57.57 0 011 5.92V3.143a.57.57 0 01.584-.556h12.832zM7.387 7.954L6.161 6.728l-.858.86L7.387 9.67l3.31-3.31-.858-.858-2.452 2.452z"
    />
  </svg>
);
export default TicketIcon;
