/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const ToFromIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M10.625 3.625L9.4 4.85l2.275 2.275h-7.35L6.6 4.85 5.375 3.625 1 8l4.375 4.375L6.6 11.15 4.325 8.875h7.35L9.4 11.15l1.225 1.225L15 8z"
    />
  </svg>
);
export default ToFromIcon;
