/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const TrackIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M11.492 9.466H4.538l-.445 1.494h7.844l-.445-1.494zm1.611 0l.445 1.494h.705a.747.747 0 010 1.493h-.26l.166.562c.156.373-.155.821-.544.896-.389.15-.778-.075-.933-.448l-.301-1.01H3.649l-.3 1.01c-.156.373-.545.597-1.012.523-.389-.15-.622-.523-.544-.896l.19-.637h-.236a.747.747 0 010-1.493h.68l.444-1.494h-.347a.747.747 0 010-1.493h.791L3.76 6.48h-.458a.747.747 0 010-1.493h.902l.7-2.35c.155-.448.544-.672 1.01-.598a.85.85 0 01.545.97l-.588 1.978h4.288L9.57 3.01a.85.85 0 01.545-.97c.389-.15.855.149.933.522l.722 2.425h.928a.747.747 0 010 1.493h-.484l.445 1.493h.817a.747.747 0 010 1.494h-.373zm-2.055-1.493l-.445-1.493H5.427l-.445 1.493h6.066z"
    />
  </svg>
);
export default TrackIcon;
