/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const TrainIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="#00367F"
      fillRule="evenodd"
      d="M1 12h13v1H1z"
      clipRule="evenodd"
    />
    <path
      fill="#00367F"
      d="M14.75 8.1a.623.623 0 00-.091-.11l-.035-.036a5.537 5.537 0 01-.093-.095c-.315-.314-2.34-1.805-3.436-2.528-.358-.236-.76-.331-.999-.331h-3.54l1.295-.89c.1-.076.149-.134.149-.256a.332.332 0 00-.142-.276L6.364 2.399H5.4l1.702 1.434-1.7 1.166h.001H1v6h12.612c.196 0 .38-.098.488-.263.49-.755.9-1.41.9-1.902 0-.277-.095-.529-.25-.735zm-2.537-.508c-.046.136-.173.172-.317.172h-.666c-.071 0-.185.01-.284-.063l-.95-.671a.332.332 0 01.2-.599h.666c.072 0 .142.024.2.068l1.034.778c.115.086.162.18.117.315z"
    />
  </svg>
);
export default TrainIcon;
