/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const TransferIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M7 5.714L2.284 1 1 2.286 5.707 7 7 5.714zM10.188 1l1.784 1.785L1 13.766 2.234 15 13.215 4.027 15 5.812V1h-4.813zm.098 8L9 10.284l2.854 2.85L9.984 15H15V9.992l-1.86 1.858L10.286 9z"
    />
  </svg>
);
export default TransferIcon;
