/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const TvmIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M7.56 10.57V6.2h-.863v4.37h.863zM9.288 8.82V6.2h-.864v2.622h.864zM4.105 3.966c0-.241.193-.437.432-.437h6.91c.239 0 .432.196.432.437v9.615a.434.434 0 01-.432.437h-2.16a.434.434 0 01-.431-.437.87.87 0 00-.864-.874.87.87 0 00-.864.874.434.434 0 01-.431.437h-2.16a.434.434 0 01-.432-.437V3.966zm10.89-.375H15v2.476c0 .372-.25.62-.626.62h-1.548V5.447h.921V4.095h-.005V2.238H2.253v3.21h.921v1.238H1.626C1.251 6.686 1 6.44 1 6.067V1.62C1 1.248 1.25 1 1.626 1h12.742c.376 0 .626.248.626.619v1.972z"
    />
  </svg>
);
export default TvmIcon;
