/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const TwitterIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M15 4.27c-.525.253-1.05.338-1.663.422.613-.338 1.05-.846 1.226-1.523-.526.339-1.138.508-1.838.677a3.109 3.109 0 00-2.1-.846c-1.488 0-2.8 1.27-2.8 2.792 0 .254 0 .423.087.593C5.55 6.3 3.363 5.2 1.963 3.508c-.262.423-.35.846-.35 1.438 0 .93.526 1.777 1.313 2.285-.437 0-.875-.17-1.312-.339 0 1.354.962 2.454 2.275 2.708-.263.085-.526.085-.788.085-.175 0-.35 0-.525-.085.35 1.1 1.4 1.946 2.712 1.946-.962.762-2.187 1.185-3.587 1.185H1C2.313 13.492 3.8 14 5.375 14c5.25 0 8.137-4.23 8.137-7.87v-.338c.613-.423 1.138-.93 1.488-1.523"
    />
  </svg>
);
export default TwitterIcon;
