/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const UnderlineIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M1 12.958h14V15H1v-2.042zM14.125 1v.875l-1.266.634a.874.874 0 00-.484.782v3.834a4.38 4.38 0 01-4.813 4.354C5.29 11.257 3.625 9.214 3.625 6.93V3.29a.874.874 0 00-.484-.781l-1.266-.634V1h5.25v.875l-1.266.634a.874.874 0 00-.484.782v3.834A2.63 2.63 0 008.523 9.7c1.246-.243 2.102-1.408 2.102-2.678V3.291a.874.874 0 00-.484-.782l-1.266-.634V1h5.25z"
    />
  </svg>
);
export default UnderlineIcon;
