/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const UnlinkIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M11.5 9.91l-1.134-1.136 1.88-1.885a2.289 2.289 0 00-1.602-3.862 2.26 2.26 0 00-1.626.63L7.142 5.552 6.001 4.409 7.88 2.514a3.873 3.873 0 015.417-.002l.044.043a3.912 3.912 0 01.047 5.475l-1.887 1.88zM4.108 6.293l1.135 1.135-1.88 1.884a2.289 2.289 0 001.602 3.864 2.26 2.26 0 001.626-.632l1.875-1.893 1.142 1.142-1.878 1.894a3.873 3.873 0 01-5.462-.04 3.911 3.911 0 01-.048-5.474l1.888-1.88zm2.492 4.228L5.485 9.408 9.6 5.292l1.115 1.114L6.6 10.521zm-5.6-8.408L2.116 1 4.96 3.845 3.845 4.959 1 2.114zm10.041 10.04l1.115-1.114L15 13.885l-1.115 1.114-2.845-2.845z"
    />
  </svg>
);
export default UnlinkIcon;
