/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const UnviewIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M13.753 5.96a11.632 11.632 0 011.135 1.613.875.875 0 010 .858c-.112.196-2.769 4.82-6.888 4.82-.475 0-.928-.067-1.362-.176l1.588-1.588c2.372-.144 4.201-2.498 4.866-3.487-.143-.212-.342-.49-.585-.793l1.246-1.246zM1.257 14.745a.874.874 0 01-.001-1.236l2.213-2.213a12.633 12.633 0 01-2.357-2.867.874.874 0 01-.001-.853C1.22 7.378 3.84 2.75 8 2.75c1.164 0 2.2.377 3.104.908l2.402-2.401a.874.874 0 111.237 1.237l-12.25 12.25a.873.873 0 01-1.237 0zm1.652-6.745c.33.493.966 1.323 1.801 2.054l1.605-1.605A1.684 1.684 0 016.25 8c0-.967.783-1.75 1.75-1.75.156 0 .305.026.448.065l1.37-1.37C9.259 4.676 8.65 4.5 8 4.5 5.503 4.5 3.59 6.98 2.91 8z"
    />
  </svg>
);
export default UnviewIcon;
