/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const UpArrowIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M7.757 7.515l4.242 4.242 1.415-1.414L9.17 6.1 7.757 4.686 2.1 10.343l1.414 1.414 4.243-4.242z"
    />
  </svg>
);
export default UpArrowIcon;
