/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const UploadIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M13.26 13.251v-2.627h1.751v3.503a.876.876 0 01-.876.876H1.876A.876.876 0 011 14.127v-3.503h1.751v2.627h10.51zM7.13 4.327L3.627 7.83 2.401 6.604 8.005 1l5.605 5.605-1.226 1.226-3.503-3.503v7.532h-1.75V4.327z"
    />
  </svg>
);
export default UploadIcon;
