/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const UpwardIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M9.138 2L7.913 3.254l3.762 3.85H1v1.792h10.675l-3.762 3.85L9.138 14 15 8z"
    />
  </svg>
);
export default UpwardIcon;
