/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const UpwardIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M2 6.862l1.254 1.225 3.85-3.762V15h1.792V4.325l3.85 3.762L14 6.862 8 1z"
    />
  </svg>
);
export default UpwardIcon;
