/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const UserIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 1c1.89 0 3.429 1.57 3.429 3.5v.875c0 1.93-1.538 3.5-3.429 3.5s-3.429-1.57-3.429-3.5V4.5C4.571 2.57 6.11 1 8 1zm3.46 8.248c1.509.502 2.54 1.65 2.54 3.127V15H2v-2.625c0-1.478 1.031-2.625 2.54-3.127.915.852 2.127 1.377 3.46 1.377s2.545-.525 3.46-1.377z"
    />
  </svg>
);
export default UserIcon;
