/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const UsersIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M9.925 10.984c.438.349.7.873.7 1.397v1.746c0 .524-.35.873-.875.873H1.875C1.35 15 1 14.65 1 14.127v-1.66c0-.523.263-1.047.7-1.396l2.362-1.834c-.787-.61-1.312-1.484-1.312-2.532v-.873c0-1.746 1.488-3.143 3.237-3.056 1.663.088 2.888 1.572 2.888 3.23v.7c0 1.047-.525 1.92-1.313 2.531l2.363 1.747zm4.287-4.366c.526.35.788.873.788 1.484v.699c0 .524-.35.873-.875.873H11.15c0-.087-1.05-.873-1.05-.873.35-.611.525-1.397.525-2.183v-.873c0-1.397-.613-2.62-1.575-3.493.438-.785 1.313-1.397 2.362-1.222S13.25 2.252 13.25 3.3v.786c0 .611-.263 1.135-.613 1.484l1.575 1.048z"
    />
  </svg>
);
export default UsersIcon;
