/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ValidationInfoIcon: IconComponentType = ({
  className,
  ...rest
}) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 6.25c-.525 0-.875-.35-.875-.875S7.475 4.5 8 4.5s.875.35.875.875-.35.875-.875.875zm.875 5.25h-1.75V7.125h1.75V11.5zM8 1C4.15 1 1 4.15 1 8s3.15 7 7 7 7-3.15 7-7-3.15-7-7-7z"
    />
    <path
      fill="#FFF"
      d="M8.875 11.5h-1.75V7.125h1.75V11.5zM8 6.25c-.525 0-.875-.35-.875-.875S7.475 4.5 8 4.5s.875.35.875.875-.35.875-.875.875z"
    />
  </svg>
);
export default ValidationInfoIcon;
