/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ValidationCheckIcon: IconComponentType = ({
  className,
  ...rest
}) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 1C4.15 1 1 4.15 1 8s3.15 7 7 7 7-3.15 7-7-3.15-7-7-7z"
    />
    <path
      fill="#FFF"
      d="M7.125 10.975L4.15 8l1.225-1.225 1.75 1.75 3.5-3.5L11.85 6.25z"
    />
  </svg>
);
export default ValidationCheckIcon;
