/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const VerticaleIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M13 6.25a1.75 1.75 0 110 3.5 1.75 1.75 0 010-3.5zm-5.25 0a1.75 1.75 0 110 3.5 1.75 1.75 0 010-3.5zm-5.25 0a1.75 1.75 0 110 3.5 1.75 1.75 0 010-3.5z"
    />
  </svg>
);
export default VerticaleIcon;
