/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ViewIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 4.667c2.484 0 4.407 2.362 5.09 3.333-.685.972-2.608 3.333-5.09 3.333-2.486 0-4.408-2.365-5.092-3.334.68-.97 2.595-3.332 5.092-3.332M8 13c4.119 0 6.776-4.403 6.887-4.59a.799.799 0 00.001-.817C14.778 7.406 12.14 3 8 3 3.84 3 1.22 7.407 1.11 7.595a.797.797 0 00.002.812C1.222 8.594 3.86 13 8 13m0-6.667c.967 0 1.75.746 1.75 1.667 0 .92-.783 1.667-1.75 1.667S6.25 8.92 6.25 8c0-.92.783-1.667 1.75-1.667"
    />
  </svg>
);
export default ViewIcon;
