/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const VimeoIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.993 4.849c-.088 1.381-1.05 3.194-2.886 5.525C10.183 12.791 8.609 14 7.297 14c-.787 0-1.487-.777-2.1-2.245-.699-2.072-1.224-6.302-2.448-6.302-.087 0-.437.26-1.05.69L1 5.282c.7-.605 3.06-2.936 4.11-3.022 1.05-.086 1.75.604 2.012 2.158.262 1.727.7 5.266 1.574 5.266.787 0 2.186-2.935 2.274-3.453.087-.777-.263-1.64-2.012-.95C9.658 3.037 10.97 2 12.894 2c1.487.086 2.186 1.036 2.099 2.849"
    />
  </svg>
);
export default VimeoIcon;
