/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const WaitingRoomIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M3.334 3.56a1.424 1.424 0 01-.342-1.962 1.39 1.39 0 011.943-.344c.627.449.78 1.32.342 1.96a1.394 1.394 0 01-1.943.346zm7.417 9.395v1.406H5.833c-1.72 0-3.182-1.265-3.447-2.982L1 4.517h1.392l1.372 6.65a2.091 2.091 0 002.062 1.788h4.925zm-3.24-2.813h3.976l2.396 3.666c.212.327.129.77-.187.989l-.113.08a.68.68 0 01-.97-.2l-1.54-2.426h-4.62A2.1 2.1 0 014.4 10.536l-.941-4.163c-.202-.95.425-1.681 1.283-1.836h.014c.23-.042.595-.008.81.08.282.114.695.308.872 1.126l1.075 4.399zM10.953 1c1.657 0 3.013 1.369 3.013 3.042s-1.356 3.042-3.013 3.042-3.013-1.37-3.013-3.042S9.295 1 10.952 1zm0 5.323c1.243 0 2.259-1.026 2.259-2.281 0-1.254-1.016-2.281-2.259-2.281s-2.26 1.027-2.26 2.28c0 1.256 1.017 2.282 2.26 2.282zm.376-3.802v1.14h1.13v.76h-1.883v-1.9h.753z"
    />
  </svg>
);
export default WaitingRoomIcon;
