/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const WalkingIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <g fill="currentColor" fillRule="evenodd" clipRule="evenodd">
      <path d="M8.663 3.5a1.25 1.25 0 110-2.499 1.25 1.25 0 010 2.499z" />
      <path d="M5.92 11.39l-.048.102-1.744 2.55a.6.6 0 10.963.716l1.905-2.297c.06-.104.116-.206.175-.31l.519-1.485-1.205-1.153-.564 1.878z" />
      <path d="M12.791 7.79l-2.026-1.244a.203.203 0 01-.064-.063l-.98-1.702a1 1 0 00-.644-.438l-1.44-.29a1 1 0 00-.797.18L5.04 5.582a1 1 0 00-.288.34L3.671 8.017a.428.428 0 00.724.456l1.293-1.996a.197.197 0 01.063-.061l1.088-.666-.309 1.533a2.294 2.294 0 00.596 2.043l2.276 2.288.045.07 1.115 2.912a.6.6 0 101.137-.384l-.805-2.874-.155-.32-1.854-2.545a.347.347 0 01-.06-.272l.374-1.857.687.871a1 1 0 00.348.28l2.12 1.03a.428.428 0 00.437-.735z" />
    </g>
  </svg>
);
export default WalkingIcon;
