/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const WarningIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.887 12.622L8.842 1.496c-.36-.661-1.325-.661-1.685 0L1.113 12.622c-.338.624.123 1.378.843 1.378h12.089c.72 0 1.18-.754.842-1.378z"
    />
    <path
      fill="#FFF"
      d="M8 12.126a.946.946 0 01-.954-.937c0-.517.427-.937.954-.937s.954.42.954.937a.946.946 0 01-.954.937zm.954-2.81H7.046V5.567h1.908v3.747z"
    />
  </svg>
);
export default WarningIcon;
