/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const WheelchairIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M7.14 3.573A1.44 1.44 0 016.802 1.6a1.376 1.376 0 011.934-.345 1.44 1.44 0 01.34 1.971 1.378 1.378 0 01-1.934.347zm1.295 8.375h1.41l-.031.111C9.326 13.79 7.75 15 5.986 15 3.788 15 2 13.177 2 10.936c0-2.14 1.639-3.922 3.732-4.057l.09-.006v1.36l-.079.008c-1.352.125-2.41 1.309-2.41 2.695 0 1.491 1.188 2.705 2.653 2.705 1.053 0 2.006-.644 2.427-1.64l.022-.053zm3.397-2.688l2.552 3.88a.71.71 0 01-.185.969l-.16.111a.678.678 0 01-.949-.18l-1.935-2.845H7.938c-.766 0-1.386-.632-1.386-1.413V5.968c0-.858.75-1.538 1.618-1.394.681.113 1.153.766 1.153 1.47V9.26h2.51z"
    />
  </svg>
);
export default WheelchairIcon;
