/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const WifiIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M8 10.5c.725 0 1.313.56 1.313 1.25S8.723 13 8 13s-1.313-.56-1.313-1.25S7.276 10.5 8 10.5zm3.063-.833c-.788-.834-1.926-1.25-3.063-1.25s-2.275.416-3.063 1.25L3.712 8.5C4.85 7.333 6.338 6.75 8 6.75s3.15.583 4.287 1.75l-1.225 1.167zM8 3c2.625 0 5.075.917 7 2.667l-1.225 1.25C12.2 5.417 10.188 4.667 8 4.667s-4.2.75-5.775 2.166L1 5.667C2.925 3.917 5.375 3 8 3z"
    />
  </svg>
);
export default WifiIcon;
