/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';

type IconProps = {
  className?: string;
};

export const YoutubeIcon: React.FC<IconProps> = ({ className, ...rest }) => (
  <svg
    className={classNames('entur-icon', className)}
    {...rest}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M6.25 10.5v-5L10.625 8 6.25 10.5zm8.575-5.167c-.175-1.083-.7-1.833-1.925-2C10.975 3 8 3 8 3s-2.975 0-4.9.333c-1.225.167-1.838.917-1.925 2C1 6.417 1 8 1 8s0 1.583.175 2.667.7 1.833 1.925 2C5.025 13 8 13 8 13s2.975 0 4.9-.333c1.225-.25 1.75-.917 1.925-2S15 8 15 8s0-1.583-.175-2.667z"
    />
  </svg>
);
export default YoutubeIcon;
