/* DO NOT CHANGE!*/
/* This file is automatically generated by a build step. Changes will be overwritten. */

import React from 'react';
import classNames from 'classnames';
import IconComponentType from '../types';

export const ZoomInIcon: IconComponentType = ({ className, ...rest }) => (
  <svg
    {...rest}
    className={classNames('entur-icon', className)}
    viewBox="0 0 16 16"
  >
    <path
      fill="currentColor"
      d="M14.996 13.78l-2.884-2.954a5.935 5.935 0 001.225-3.653C13.337 3.783 10.625 1 7.212 1S1 3.782 1 7.173c0 3.392 2.8 6.174 6.212 6.174 1.4 0 2.712-.434 3.675-1.217L13.772 15l1.224-1.22zm-7.784-2.259c-2.45 0-4.462-1.913-4.462-4.348 0-2.434 2.012-4.434 4.462-4.434s4.462 2 4.462 4.434c0 2.435-2.012 4.348-4.462 4.348zm.455-6.52H6.334v1.333H5v1.333h1.334V9h1.333V7.667H9V6.334H7.667V5z"
    />
  </svg>
);
export default ZoomInIcon;
