import React from 'react';
import ReactMarkdown from 'markdown-to-jsx';

import { Badge, Tag } from '@entur/layout';
import { BackArrowIcon, BugIcon, NewIcon, WarningIcon } from '@entur/icons';
import {
  CodeText,
  Heading3,
  Heading6,
  Link,
  ListItem,
  Paragraph,
  StrongText,
  UnorderedList,
} from '@entur/typography';

import './MarkdownParser.scss';

// Beta entries get their own sections, marked with a badge instead of the
// suffix the changelog preset writes.
const BETA_SUFFIX = ' (beta)';

// The changelog groups entries under headings generated by our
// conventional-changelog preset.
const SECTION_ICONS: Record<string, React.ElementType> = {
  'Bug Fixes': BugIcon,
  Features: NewIcon,
  'BREAKING CHANGES': WarningIcon,
  Reverts: BackArrowIcon,
};

const textContent = (children: React.ReactNode): string =>
  React.Children.toArray(children)
    .map(child => {
      if (typeof child === 'string') return child;
      if (React.isValidElement(child)) return textContent(child.props.children);
      return '';
    })
    .join('');

const isParagraph = (node: React.ReactNode) =>
  React.isValidElement(node) && (node.type === Paragraph || node.type === 'p');

export const ChangelogSection = ({
  children,
  ...rest
}: {
  children?: React.ReactNode;
}) => {
  // Beta components have their own sections, e.g. "Bug Fixes (beta)".
  const heading = textContent(children).trim();
  const isBeta = heading.endsWith(BETA_SUFFIX);
  const title = isBeta ? heading.slice(0, -BETA_SUFFIX.length) : heading;
  const Icon = SECTION_ICONS[title];

  // Rendered as a heading: the sections structure the changelog, and sit one
  // level below the version they belong to.
  return (
    // markdown-to-jsx passes a className of its own, so it goes first.
    <h4 {...rest} className="markdown-parser__section">
      <Tag as="span">
        {Icon ? <Icon aria-hidden="true" /> : null}
        {title}
        {isBeta && (
          <Badge type="status" variant="neutral">
            beta
          </Badge>
        )}
      </Tag>
    </h4>
  );
};

/** Et changelog-innslag er én commit: overskriften, og eventuelt den lengre
 * beskrivelsen fra commit-meldingen. */
export const ChangelogEntry = ({
  children,
  ...rest
}: {
  children?: React.ReactNode;
}) => {
  const blocks = React.Children.toArray(children);
  const [summary, ...description] = blocks;

  // Entries without a description are inline content, not blocks.
  if (!isParagraph(summary) || description.length === 0) {
    return <ListItem {...rest}>{children}</ListItem>;
  }

  return (
    <ListItem {...rest}>
      {(summary as React.ReactElement).props.children}
      <div className="markdown-parser__description">{description}</div>
    </ListItem>
  );
};

export const MarkdownParser: React.FC<{ children: any }> = ({ children }) => {
  return (
    <ReactMarkdown
      className="markdown-parser"
      options={{
        overrides: {
          // Releases are h1 when the version got a minor or major bump and h2
          // when it got a patch, but they are the same thing to a reader.
          h1: { component: Heading3 },
          h2: { component: Heading3 },
          h3: { component: ChangelogSection },
          h4: { component: Heading6 },
          h5: { component: Heading6 },
          a: { component: Link },
          p: { component: Paragraph },
          ul: { component: UnorderedList },
          li: { component: ChangelogEntry },
          strong: { component: StrongText },
          code: { component: CodeText },
        },
      }}
      lang="en"
    >
      {children}
    </ReactMarkdown>
  );
};
