name: 'Manage Nx cache'
description: 'Downloads Nx cache and updates it after run'
runs:
  using: 'composite'
  steps:
    - name: Cache Nx
      uses: actions/cache@v4
      with:
        path: '.cache/nx'
        key: nx-${{ runner.os }}-${{ github.run_id }} # Since this is unique the cache will always be updated
        restore-keys: nx-${{ runner.os }} # But since this one always matches we will also always get a cache hit
