name: Build, test and deploy to preview channel

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-packages:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install and Cache Yarn Dependencies
        uses: ./.github/actions/install-and-cache-dependencies
        with:
          cache-key: yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Use Nx cache
        uses: ./.github/actions/use-nx-cache

      - run: NX_REJECT_UNKNOWN_LOCAL_CACHE=0 yarn build:packages

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-artifacts
          path: 'packages/**/dist'

  build-documentation:
    name: Build documentation
    needs: build-packages
    runs-on:
      group: 'grp-ubuntu-22.04-4core-x64'
    steps:
      - uses: actions/checkout@v4

      - name: Install and Cache Yarn Dependencies
        uses: ./.github/actions/install-and-cache-dependencies
        with:
          cache-key: yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-artifacts
          path: 'packages'

      - name: Cache gatsby
        uses: actions/cache@v4
        with:
          path: |
            apps/documentation/.cache
            apps/documentation/public
          key: gatsby-${{ runner.os }}-${{ github.run_id }} # Since this is unique the cache will always be updated
          restore-keys: gatsby-${{ runner.os }} # But since this one always matches we will also always get a cache hit

      - run: yarn build:documentation:skip-packages-dependency

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-site-artifact
          path: apps/documentation/public

  test-packages:
    name: Test packages
    needs: build-packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install and Cache Yarn Dependencies
        uses: ./.github/actions/install-and-cache-dependencies
        with:
          cache-key: yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-artifacts
          path: 'packages'

      - run: yarn test

  lint-packages:
    name: Lint packages
    needs: build-packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install and Cache Yarn Dependencies
        uses: ./.github/actions/install-and-cache-dependencies
        with:
          cache-key: yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Use Nx cache
        uses: ./.github/actions/use-nx-cache

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-artifacts
          path: 'packages'

      - run: yarn lint

  deploy-documentation-to-preview-channel:
    needs: build-documentation
    uses: entur/gha-firebase/.github/workflows/firebase-hosting-preview.yml@v1
    with:
      gcp_project_id: entur-design-system
      environment: prd
      build_artifact_name: documentation-site-artifact
      build_artifact_path: 'apps/documentation/public'
      entry_point: 'apps/documentation'
