name: build-test-and-approval-deploy

on:
  push:
    # branches:
    #   - "main"

concurrency:
  group: 'yarn-build'
  cancel-in-progress: true

jobs:
  build-packages:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: yarn-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile --cache-folder node_modules/.cache/yarn

      - run: yarn build:packages

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-artifacts
          path: 'packages/**/dist'

  build-documentation:
    name: Build documentation
    needs: build-packages
    runs-on:
      group: 'grp-ubuntu-22.04-4core'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: yarn-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile --cache-folder node_modules/.cache/yarn

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-artifacts
          path: 'packages'

      - run: yarn build:documentation

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-site-artifact
          path: apps/documentation/dist

  deploy-documentation-to-preview-channel:
    needs: build-documentation
    uses: entur/gha-firebase/.github/workflows/firebase-hosting-preview.yml@v1
    with:
      gcp_project_id: entur-design-system
      environment: prd
      build_artifact_name: documentation-site-artifact
      build_artifact_path: 'apps/documentation/dist'
      entry_point: 'apps/documentation'
