import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import { visit } from 'unist-util-visit';

const docsDir = path.resolve(
  __dirname,
  '../../../documentation/src/pages/komponenter',
);
const outputPath = path.resolve(
  __dirname,
  '../snippets/snippetsAutogenerated.ts',
);

const snippets: { group: string; name: string; code: string }[] = [];

function getTitle(content: string, filename: string) {
  const { data } = matter(content);
  return data?.title || filename.replace(/\.mdx?$/, '');
}

function inferNameFromCode(code: string): string {
  const match = code.match(/<([A-Z][a-zA-Z]+)/);
  return match ? `<${match[1]}>` : code.trim().split('\n')[0].slice(0, 40);
}

function extractCodeBlocks(filePath: string) {
  const fileContent = fs.readFileSync(filePath, 'utf8');
  const title = getTitle(fileContent, path.basename(filePath));
  const tree = unified().use(remarkParse).use(remarkGfm).parse(fileContent);

  visit(tree, 'code', (node: any) => {
    if (node.lang === 'jsx' || node.lang === 'tsx') {
      snippets.push({
        group: title,
        name: `${title}: ${inferNameFromCode(node.value)}`,
        code: node.value.trim(),
      });
    }
  });
}

function walk(dir: string) {
  fs.readdirSync(dir).forEach(file => {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      walk(fullPath);
    } else if (file.endsWith('.mdx')) {
      extractCodeBlocks(fullPath);
    }
  });
}

walk(docsDir);

const out = `const snippets = ${JSON.stringify(
  snippets,
  null,
  2,
)};\nexport default snippets;\n`;
fs.writeFileSync(outputPath, out);

console.log(`✅ Generated ${snippets.length} snippets to ${outputPath}`);
